#!/bin/sh
#
#  ifup [interface name|definition file]
#
. /usr/share/ifupfn.sh

devfn=$1
[ $# -gt 0 ] && shift

case "$devfn" in
  "")  #take the interface definitions from the environment
    [ "${DEVICE}" ] || usage
    ifup_function
  ;;
  
  */*) #assume anything with a / is the path to an interface definition file
    unset DEVICE BOOTPROTO IPADDR NETMASK BROADCAST DHCPNAME
    unset NETWORK GATEWAY NSprepCMD
    . $devfn
    ifup_function "$@"
  ;;
  
  -*)  #any flag is a request for help
    usage    
  ;;
  
  *) #anything else must be the name of an interface
    unset DEVICE BOOTPROTO IPADDR NETMASK BROADCAST DHCPNAME
    unset NETWORK GATEWAY NSprepCmd
    . /etc/sysconfig/ifcfg-$devfn
    ifup_function "$@"
  ;;
esac
