#!/bin/sh
#initialize slip link's ip parameters

unset DEVICE BOOTPROTO IPADDR NETMASK BROADCAST DHCPNAME
unset NETWORK GATEWAY NSprepCmd MTU AUTOSTART
. /etc/sysconfig/ifcfg-$1
IPADDR=$SLIPADDR
. /usr/share/ipinit.sh
