#!/bin/sh
#initialize slip link's ip parameters

. /usr/share/netutils.sh

[ "$1" ] && DEVICE=$1
unset BOOTPROTO IPADDR NETMASK BROADCAST DHCPNAME
unset NETWORK GATEWAY MTU AUTOSTART
. /etc/sysconfig/ifcfg-$DEVICE
IPADDR=$SLIPADDR ipUp
:
