#!/bin/bash
# unpack & configure dnsmasq for arm-linux -- 3/22/21 brent@mbari.org
: ${gitTop:=~/git}
: ${dnsmasqTop:=$gitTop/dnsmasq}

top=$PWD
[ -e "$dnsmasqTop" ] || {
  cd $gitTop &&
  git clone -b v2.9 git://thekelleys.org.uk/dnsmasq.git || exit
}
echo "Now, run arminstall"
