#!/bin/bash
# unpack & configure dnsmasq for arm-linux -- 4/5/21 brent@mbari.org
# note that dnsmasq v2.84 is last release with support for tftp-server
: ${gitTop:=`realpath $(dirname $0)`}
vers=v2.84
: ${dnsmasqTop:=$gitTop/dnsmasq-$vers}
[ -d "$dnsmasqTop" ] || {
  cd $gitTop &&
  git clone -b $vers git://thekelleys.org.uk/dnsmasq.git $dnsmasqTop || exit
}
echo "Now, run arminstall"
