#!/bin/sh
# build & install dnsmasq from openwrt to arm-linux
# -- 4/5/21 brent@mbari.org

: ${gitTop:=`dirname $0`}
vers=v2.84
: ${dnsmasqTop:=$gitTop/dnsmasq-$vers}
: ${HOSTTOP:=${1-$HOME/armHost}}
: ${HOST:=$ARMHOST}

here=$PWD
echo "Installing dnsmasq in $HOSTTOP"
cd $dnsmasqTop || exit $?
make clean && 
make CC=$HOST-gcc COPTS="-DNO_INOTIFY -DNO_IPV6 -DNO_DHCP6" &&
$HOST-strip -o $HOSTTOP/usr/sbin/dnsmasq src/dnsmasq &&
cd $here &&
[ -e $HOSTTOP/etc/dnsmasq.conf ] || cp dnsmasq.conf $HOSTTOP/etc &&
cp dnsmasq $HOSTTOP/etc/rc.d/init.d &&
echo "Done."
