#!/bin/sh
PATH=/usr/sbin:/sbin:/bin
daemon=dnsmasq
pidfn=/run/$daemon.pid
OPTIONS="--group=daemon"

stop() {
  pid=`cat $pidfn 2>/dev/null` && [ "$pid" ] && {
    echo "Stopping $daemon"
    kill $pid 2>/dev/null && {
      usleep 200000
      for i in 1 2 3 4 5 6 7 8 9; do
        kill -0 $pid 2>/dev/null || return
        sleep 1
      done
      echo "$daemon not responding to TERM signal" >&2
      return 1
    }
  }
  rm -f $pidfn
}

case "$1" in
  start|restart)
    stop
    echo "Starting $daemon..."
    mkdir -p /card/tftp
    $daemon $OPTIONS
;;
  stop)
    stop
;;
  *)
    echo "usage: $daemon {start|stop|restart}"
esac
