#!/bin/sh
PATH=/usr/sbin:/sbin:/bin
daemon=dnsmasq
pidfn=/run/$daemon.pid
OPTIONS="--group=daemon"

getpid() {
  pid=`cat $pidfn 2>/dev/null` && [ "$pid" ]
}

stop() {
  getpid && {
    echo "Stopping $daemon"
    kill $pid 2>/dev/null && {
      usleep 200000
      for i in 1 2 3 4 5 6 7 8 9; do
        kill -0 $pid 2>/dev/null || return
        sleep 1
      done
      echo "$daemon not responding to TERM signal" >&2
      return 1
    }
  }
  rm -f $pidfn
}

start() {
  echo "Starting $daemon..."
  mkdir -p /card/tftp /run/dnsmasq
  $daemon $OPTIONS
}

case "$1" in
  start|restart)
    stop
    start
;;
  stop)
    stop
;;
  reload)
    if getpid; then
      echo "Reloading $daemon..."
      kill -HUP $pid
    else
      start
    fi
;;
  *)
    echo "usage: $daemon {start|stop|restart|reload}"
esac
