#!/bin/sh
#catch up all pending udev ifup operations

lockFn=/var/lock/ifup.pending
[ -r $lockFn ] || exit
exec 7<$lockFn
flock -xw 60 7 || {
  echo "Cannot lock $lockFn" >&2
  exit 1
}
read -r ifNames <&7 || [ $? = 1 ] || {
  echo "Cannot read $lockFn" >&2
  exit 2
}
rm $lockFn  #before giving up lock!
exec 7<&-

. /usr/share/netutils.sh

delay=
for iface in $ifNames; do
  case $iface in
    [0-9]*) delay=$iface
  ;;
    *) ifCfg $iface
       ifUp "''|y|yes|1|true" $delay &  #only if AUTOSTART missing,yes, or true
       delay=
  esac
done
