#!/bin/sh
#finish all pending udev ifup operations

lockFn=/run/ifup.pending
[ -r $lockFn ] || exit
exec 7<$lockFn
flock -xw 60 7 || {
  echo "Cannot lock $lockFn" >&2
  exit 1
}
read -r ifNames <&7 || [ $? = 1 ] || {
  echo "Cannot read $lockFn" >&2
  exit 2
}
rm $lockFn  #before giving up lock!
exec 7<&-

. /usr/share/netutils.sh

delay=
for iface in $ifNames; do
  case $iface in
    [0-9]*) IFS=. read now idle </proc/uptime  #uptime in secs
            let "iface>now" && let "delay=iface-now"
  ;;
    *) ifCfg $iface && notUnplugged && ifUpAuto $delay &
       delay=
  esac
done
wait
