#!/usr/bin/setsid /bin/sh
#setsid because udev requires blocking processes to detach
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
/usr/sbin/ifdown $INTERFACE
# remove any symlinks to this modem's ports under /dev/AT
store=/run/link
ifFn="$store/$INTERFACE"
exec 5<$ifFn && cd /dev && flock -w60 5 || exit
while read kernelDev template <&5; do
  newName=${template/'#'/$INTERFACE}
#  echo "removing $newName" >>/tmp/console
  rm $newName
done
keyFn=`realpath $ifFn` && rm $keyFn $store/if-`basename $keyFn` $ifFn
