#!/usr/bin/setsid /bin/sh
#setsid because udev requires blocking processes to detach
[ "$2" ] || {
  echo add symlinks for all values of key \$1 >&2
  echo   substituting interface \$2 for first \'#\' in each >&2
  exit 1
}

#exec 2>>/tmp/ifLink
#date >&2
#env >&2
#set -x

INTERFACE=$2
case $INTERFACE in
 eth*|wlan*) exit 0  #ignore non-modems
esac
store=/run/link
ifFn="$store/$INTERFACE"
keyFn="$store/$1"
mkdir -p $store
cd /dev && >>$keyFn && exec 5<$keyFn && flock -w60 5 &&
echo $INTERFACE >"$store/if-$1" && ln -sf "$1" $ifFn || exit
#echo stored iface: $INTERFACE >>/tmp/console
while read kernelDev template <&5; do
  newName=${template/'#'/$INTERFACE}
#  echo "ifLink $kernelDev => $newName" >>/tmp/console
  mkdir -p `dirname $newName`
  ln -sf /dev/$kernelDev $newName
done
