#!/usr/bin/setsid /bin/sh
#setsid because udev requires blocking processes to detach
[ "$2" ] || {
cat >&2 <<END
Some Ethernet modems need an initial AT command to connect
First argument is the path to the modem's AT command port
2nd argument is the string to send
3rd {optional} argument is delay in seconds before sending
END
exit 2
}
( [ "$3" ] && sleep $3; flock -w180 $1 /usr/sbin/chat '' "$2" OK <$1 >$1) &
