#!/bin/sh
#prompt for login (once)
#ignore during coldplugging
[ -e "/run/coldplugged" ] || exit 0
tag="`basename $0`[$$]"
dev=${1-$DEVNAME}
baud=${2-115200}
[ "$dev" ] || {
  logger -t $tag -perr Missing tty device path
  exit 2
}
node=`readlink -f "$dev"` && [ -c "$node" ] || {
  logger -t $tag -perr "Invalid login device: $dev"
  exit 3
}
loginDev=${node}.login
cp -a $dev $loginDev || {
  logger -t $tag -perr "Cannot create login device: $loginDev"
  exit 4
}
tty=${loginDev#/dev/}
logger -t $tag Accepting login on $tty @$baud baud for 30 seconds
(/sbin/getty -L $baud ${3-"-wt30"} $tty; rm $loginDev) &
