#!/bin/sh
[ "$1" ] || {
  cat >&2 <<-END
Bring up/down ppp network interface handled by serial modem
First argument should be the interface name (ppp*)
END
  exit 2
}
[ -w /tmp/ttyModem ] && {
  exec 2>>/tmp/ttyModem
  date >&2
  env >&2
  set -x
}

case "$ACTION" in
  add) #this modem replaces any other
    ln -sf $DEVNAME /dev/modem
    sleep 3
    exec /usr/sbin/ifup $1
  ;;
  remove)
    exec /usr/sbin/ifdown $1
esac
