#!/bin/bash
# configure libzlib-1.2.2 build for arm-linux -- 3/15/05 brent@mbari.org
: ${CFLAGS:=-Os}
: ${CXXFLAGS:=$CFLAGS}
: ${ARMGCC:=/arm}
: ${CC:=$ARMGCC/bin/gcc}
: ${LIBTOP:=${1-$ARMGCC}}
: ${ZLIBVERS:=zlib-1.2.2}
export CC CFLAGS CXXFLAGS
rm -rf $ZLIBVERS && tar xzf $ZLIBVERS.tar.gz && cd $ZLIBVERS &&
#bash_cv_have_mbstate_t=yes bash_cv_func_sigsetjmp=present \
#ac_cv_func_strcoll_works=yes bash_cv_func_strcoll_broken=no \
#bash_cv_must_reinstall_sighandlers=no 
configure --shared --prefix=$LIBTOP  --includedir=$ARMGCC/include &&
echo "Next, run arminstall here"
