#!/bin/bash
# configure setserial-2.17 build for arm-linux -- 3/15/05 brent@mbari.org
: ${CFLAGS:="-Os -fomit-frame-pointer"}
: ${CXXFLAGS:=$CFLAGS}
: ${ARMGCC:=/arm}
: ${CC:=$ARMGCC/bin/gcc}
: ${LIBTOP:=${1-$ARMGCC}}
: ${SETSERVERS:=setserial-2.17}
export CC CFLAGS CXXFLAGS
rm -rf $SETSERVERS && tar xzf setserial-2.17gentoo.tar.gz && cd $SETSERVERS &&
configure --host=arm-unknown-linux --prefix=$LIBTOP --includedir=$ARMGCC/include &&
echo "Next, run arminstall here"
