#!/bin/sh
# build & install setserial for arm-linux -- 3/15/05 brent@mbari.org

: ${ARMGCC:=/arm}
: ${ARMSTRIP:=$ARMGCC/bin/strip}
: ${TARGETTOP:=${2-/bin}}
: ${HOSTTOP:=${1-$HOME/armHost$TARGETTOP}}
echo "Installing in $HOSTTOP"
echo "  for execution at $TARGETTOP on the ARM target"
cd ${SETSERVERS-setserial-2.17} || exit 2
make CFLAGS="-Os -fomit-frame-pointer" CC=/arm/bin/gcc &&
$ARMSTRIP setserial &&
install -Dm 755 setserial $HOSTTOP/setserial || exit 1
echo "Done."
