#!/bin/sh
# netplugd 'policy script'
#  revised 10/31/21 brent@mbari.org

export PATH=/bin:/sbin:/usr/bin:/usr/sbin

[ "$#" != 2 ] && {
  echo "Error: should be called from netplugd" >&2
  exit 1
}

exec >/dev/console 2>&1
. /usr/share/netutils.sh

log() {
    logger -t "netplugd[$PPID]" -p daemon.$1 "$interface: $2"
}

dev="$1"
act="$2"
case "$act" in
  in)     ifCfg $dev && ifUpAuto
;;

  out)    ifCfg $dev && ifDown
          exec /sbin/ifconfig $dev 0  #clear IP adr to force reconfig
;;

  probe)  exec /sbin/ifconfig $dev down >/dev/null 2>&1
;;

*)  log err "Unknown netplugd command: $act on $dev"
    exit 1
esac
:
