#!/bin/sh
# netplugd 'policy script'
#  revised 1/15/26 brent@mbari.org

export PATH=/bin:/sbin:/usr/bin:/usr/sbin

[ "$#" != 2 ] && {
  echo "Error: should be called from netplugd" >&2
  exit 1
}

log() {
    logger -t "netplugd[$PPID]" -p daemon.$1 "$interface: $2"
}

. /usr/share/netutils.sh

dev="$1"
act="$2"
#log notice "$dev $act"
case "$act" in
  in)     ifCfg $dev && ifUpAuto
;;
  out)    ifCfg $dev && ifDown 0  #don't DOWN iface, just clear its IP address
;;
  probe)  #ignore or ifconfig $dev up 0 >/dev/null 2>&1
;;
  *)      log err "Unknown action: $act on $dev"
          exit 1
esac
:
