#!/bin/bash
# unpack & configure GNU screen for arm-linux -- 4/5/21 brent@mbari.org
: ${gitTop:=`realpath $(dirname $0)`}
: ${screenTop:=$gitTop/screen/src}
: ${HOST:=$ARMHOST}

[ -d "$screenTop" ] || {
  cd $gitTop &&
  git clone -b v.4.8.0 https://git.savannah.gnu.org/git/screen.git $screenTop ||
    exit
}
cd "$screenTop" || exit
[ -d configure ] || autogen.sh
configure --host=$HOST CC=$HOST-gcc \
 --enable-socket-dir --enable-telnet --disable-pam \
 CPPFLAGS=-I$ARMPREFIX/include LDFLAGS=-L$ARMPREFIX/lib &&
echo "Now, run arminstall"
