#!/bin/sh
# build & install GNU screen to arm-linux
# -- 3/22/21 brent@mbari.org

: ${gitTop:=~/git}
: ${screenTop:=$gitTop/screen/src}
: ${HOSTTOP:=${1-$HOME/armHost}}
: ${HOST:=$ARMHOST}

here=$PWD
echo "Installing GNU screen in $HOSTTOP"
cd $screenTop || exit $?
make clean && 
make -j4 CC=$HOST-gcc &&
$HOST-strip -o $HOSTTOP/usr/bin/screen screen &&
cd $here &&
echo "Done."
