#!/bin/bash
# unpack and configure ppp for arm-linux -- 8/5/08 brent@mbari.org
: ${CFLAGS:="-Os -fomit-frame-pointer"}
: ${CXXFLAGS:=$CFLAGS}
: ${ARMGCC:=/arm}
: ${CC:=$ARMGCC/bin/gcc}
: ${LIBTOP:=${1-$ARMGCC}}
: ${TOOLVERS:=net-tools-1.60}
export CC CFLAGS CXXFLAGS
rm -rf $TOOLVERS && tar xzf $TOOLVERS.tgz && cp slattach.c $TOOLVERS &&
cd $TOOLVERS && echo "Next, run arminstall here"
