#!/bin/sh
# unpack and configure linux24 for arm-linux -- 3/21/06 brent@mbari.org
#  This is still not completely automated!
#
#  The patched kernel source from technologists can be downloaded with:
# wget http://www.embeddedarm.com/downloads/arm_sbc/linux24-ts9-ksrc.tar.gz

# rm -rf linux24

# (update linux24 subdir from CVS)

#  merge/untar source with:
# tar --keep-old-files --exclude CVS -xzf linux24-ts9-ksrc.tar.gz

cp ts7200.config linux24/.config
#cd linux24 && make menuconfig #--simply save back the config to .config

