#!/bin/sh
# build & install GNU iproute2 to arm-linux
# -- 4/23/21 brent@mbari.org

: ${gitTop:=`dirname $0`}
: ${iproute2Top:=$gitTop/iproute2}
: ${HOSTTOP:=${1-$HOME/armHost}}
: ${HOST:=$ARMHOST}

here=$PWD
echo "Installing GNU screen in $HOSTTOP"
cd $iproute2Top || exit
make clean && 
make -j4 &&
for bin in ip/ip ip/rtmon misc/nstat misc/rtacct misc/ss misc/ifstat misc/lnstat; do
  $HOST-strip -o $HOSTTOP/sbin/$(basename $bin) $bin || exit
done
echo "Done."
