#!/bin/sh
#  unpack, patch, build and install all MBARI embedded linux packages 
#  for now, we get away without dealing with interpackage build
#  dependencies. 
#
#  Also remove read permissions from password files as git doesn't seem to 
#  preserve permissions other than the executable bit.
#
if [ "$1" ]; then
  dirs="$*"
else
  dirs="
   glibc zlib sysvinit busybox dropbear slattach portmap ppp scripts setserial
   vsftpd thttpd util-linux e2fsprogs net-tools wireless_tools"
   # flashutil builds flash_eraseall
fi

mksymlinks ~/armHost "rm -f" < symlinks

for dir in $dirs; do
  [ -d $dir ] && [ $dir != CVS ] && (
    echo
    echo "BUILDING $dir:"
    cd $dir
    [ -x armconfig ] && { armconfig || exit $?; }
    [ -x arminstall ] && { arminstall || exit $?; }
  )
done

cd ~/armHost/etc
chmod og-r shadow ppp/*secrets

echo "now run buildjffs2 > [imageFile.jffs2]"
