#!/bin/sh
#  unpack, patch, build and install all MBARI embedded linux packages 
#  for now, we get away without dealing with interpackage build
#  dependencies.  This may change in future...  -- 5/28/05 brent@mbari.org
#  This future is now... -- 1/25/06 brent@mbari.org

if [ "$1" ]; then
  dirs="$*"
else
  dirs="
   glibc zlib sysvinit busybox dropbear slattach portmap ppp scripts setserial
   vsftpd util-linux e2fsprogs net-tools wireless_tools"
   # flashutil builds flash_eraseall
fi

mksymlinks ~/armHost "rm -f" < symlinks
for dir in $dirs; do
  [ -d $dir ] && [ $dir != CVS ] && (
    echo
    echo "BUILDING $dir:"
    cd $dir
    [ -x armconfig ] && { armconfig || exit $?; }
    [ -x arminstall ] && { arminstall || exit $?; }
  )
done

echo "now run buildjffs2 > [imageFile.jffs2]"
