#!/bin/sh -e
# Rebuild the entire ESP Linux base OS for the TS-7200
#   -- revised:  12/28/10 brent@mbari.org

cd ~/linux/esp
arminstall  #this builds the filesystem tree rooted at ~/armHost

echo Add Ruby and its supporting libs
cd ~/ESP/gen2/software
cd termcap
arminstall
cd ../readline
armconfig && arminstall
cd ../ruby
armconfig && arminstall


echo Add Tiff libraries and snap application

cd ~/ESP/gen2/software/libtiff
armconfig && arminstall

cd ../camera/starlight
make clean arm/snap
/arm/bin/strip arm/snap
mkdir -p ~/armHost/usr/local/bin
cp arm/snap ~/armHost/usr/local/bin


echo Add picocom and lrzsz

cd ~/linux/picocom
make CC=/arm/bin/gcc clean picocom
/arm/bin/strip picocom
cp picocom ~/armHost/usr/local/bin

cd ~/linux/lrzsz
armconfig && arminstall
