#!/bin/bash -e
rm -rf ~/armHost
cd ~/linux/esp
arminstall  #this builds the filesystem tree rooted at ~/armHost

# Add Ruby and its supporting libs to the base tree

cd ~/ESP/gen2/software
cd termcap
arminstall
cd ../readline
armconfig && arminstall
cd ../ruby
armconfig && arminstall


# Add Tiff libraries and snap application

cd ~/ESP/gen2/software/libtiff
armconfig && arminstall

cd ../camera/starlight
make clean arm/snap
/arm/bin/strip arm/snap
mkdir -p ~/armHost/usr/local/bin
cp arm/snap ~/armHost/usr/local/bin


# Add picocom and lrzsz

cd ~/linux/picocom
make CC=/arm/bin/gcc clean picocom
/arm/bin/strip picocom
cp picocom ~/armHost/usr/local/bin

cd ~/linux/lrzsz
armconfig && arminstall

# install the kernel modules

cd ~/linux/technologic/linux24
make modules_install

# Create the JFFS2 filesystem image

cd ../../esp
buildjffs2 > armHost.jffs2
