#!/bin/sh
[ "$2" ] || {
  echo "$0 is wpa_cli hook where \$1=iface \$2=action"
  exit 9
}

log() {
    logger -st "wpa_cli[$PPID]" -p daemon.$1 "${IFALIAS:-$IFNAME} $2"
}

[ -t 1 ] || exec >/dev/console 2>&1
wpaConnected() {
  :
}
. /usr/share/netutils.sh
ifCfg $1

case "$2" in
  CONNECTED)
    log notice "connected${WPA_ID_STR:+" to $WPA_ID_STR"}"
    wpaConnected && preppedIfUp
;;
  DISCONNECTED|stop|down)
    log notice "disconnected${WPA_ID_STR:+" from $WPA_ID_STR"}"
    for dhcp in $run/*dhcpc*-$IFNAME; do   #kill only the dhcpc daemons, not wpa
      dhcpPID=`cat $pidFn 2>/dev/null` && [ "$dhcpPID" ] && kill "$dhcpPID"
    done
;;
  reload|check)
    log info "unimplemented action \"$2\""
;;
  *)
    log err "unknown action: \"$2\""
    exit 1
esac
:
