#!/bin/sh
#wpa_cli action script to start dhcp after client is associated on interface
WPA_IFACE="$1"
WPA_ACTION="$2"

exec >/dev/console 2>&1

. /usr/share/netutils.sh

case "$WPA_ACTION" in
  CONNECTED)
    wpaConnected() {
      :
    }
    ifCfg $1
    ifn=${IFALIAS:-$IFNAME}
    logger -st wpa -p info "$ifn connected${WPA_ID_STR+" to $WPA_ID_STR"}"
    wpaConnected && preppedIfUp
;;
  DISCONNECTED|stop|down)
    for dhcp in $run/*dhcpc*-$IFNAME; do   #kill only the dhcpc daemons, not wpa
      dhcpPID=`cat $pidFn 2>/dev/null` && [ "$dhcpPID" ] && kill "$dhcpPID"
    done
;;
  reload|check)
    logger -t wpa_cli -p info "Unimplemented action \"$WPA_ACTION\""
;;
  *)
    logger -st wpa_cli -p err "Unknown action: \"$WPA_ACTION\""
    exit 1
esac
:
