#!/bin/sh
# build & install ser2net daemon for arm-linux -- 4/12/16 brent@mbari.org

: ${ARMGCC:=/arm}
: ${CC:=$ARMGCC/bin/gcc}
: ${LD:=$ARMGCC/bin/ld}
: ${CFLAGS:="-Os -fomit-frame-pointer"}
: ${TARGETBIN:=${2-/usr/sbin}}
: ${TARGETLIB:=${2-/usr/lib}}
: ${HOSTTOP:=${1-$HOME/armHost}}
: ${NETDEVVERS:=cyclades-serial-client-0.93}
HOSTBIN=$HOSTTOP/$TARGETBIN
HOSTLIB=$HOSTTOP/$TARGETLIB
echo "Installing in $HOSTBIN, libs to $HOSTLIB"
echo "  for execution at $TARGETBIN on the ARM target"
top=`pwd` &&
cd ${NETDEVVERS} || exit 2
make CC=$CC LD=$LD CCFLAGS="$CFLAGS" &&
install -Dm 755 cyclades-ser-cli $HOSTBIN/netdev &&
install -Dm 755 libcsc/libcyclades-ser-cli.so $HOSTLIB/netdev.so || exit 1
echo "Done."
