#!/bin/bash
# unpack & configure uboot enviroment tools  for arm-linux -- 6/5/21 brent@mbari.org
: ${gitTop:=`realpath $(dirname $0)`}
repo=uboot-env.git
: ${ubootEnvTop:=$gitTop/$repo}
: ${HOST:=$ARMHOST}

[ -d "$ubootEnvTop" ] || {
  cd $gitTop &&
  git clone git@github.com:brentr/$repo $ubootEnvTop &&
  cd $ubootEnvTop || #&& git checkout 782e4f93f2b4324b ||
    exit
}
echo "Now, run arminstall"
