#!/bin/sh
#reconfigure ks8851_mll -- see /etc/modprobe.d/ether.conf
#Switch to energy saver mode with rate limted to 10Mb/sec
#This will cause our interface to shutdown completely a few seconds after being
#disconnected from its peer.
#Only plugging the port into an *active* peer will reactivate the interface.
#Energy saving ethernet switches shut down ports after being disconnected.
#If both ends are shut down, neither will awaken when reconnected.

ifconfig eth0 up 0  #start determining whether cable is connected

#exit  #uncomment this to run Ethernet at 100Mb/sec and disable energy saver

cd /sys/module/ks8851_mll/parameters &&
echo 2 >power &&
echo 0x8093 >p1cr

