#!/bin/sh
#Start a gdb session with the (local) openocd target -- 11/19/14 brent@mbari.org
#***  unplug/replug USB to JTAG dongle before running ***
cd `dirname $0`
export CROSS_COMPILE=arm-none-linux-gnueabi-
: ${targetLog:=lpc313x.log}
: ${GDBstart:=start.gdb}
: ${GDB:=${CROSS_COMPILE}gdb}

openocd --log $targetLog &
ocdpid=$!
trap "exec 2>/dev/null; kill $ocdpid && wait $!" EXIT INT QUIT HUP PIPE

echo "==>  \`tail -f $targetLog\` to monitor target debug log  <=="
sleep 2
$GDB -x $GDBstart "$@"
