#!/bin/sh
# install libc for arm-linux -- 3/15/05 brent@mbari.org

: ${ARMGCC:=/arm}
: ${ARMSTRIP:=$ARMGCC/bin/strip}
: ${TARGETTOP:=${2-/lib}}
: ${HOSTTOP:=${1-$HOME/armHost$TARGETTOP}}
echo "Installing in $HOSTTOP"
echo "  for execution at $TARGETTOP on the ARM target"
: ${LIBCVERS:=2.2.5}
LIB=$ARMGCC/lib
STRIP=$ARMGCC/bin/strip

cplinks() {
#recursively copy symlinks having the specified target $1
  for target in `find -lname "$1"`; do
    cp -a $target $HOSTTOP || return $?
    cplinks $target
  done
}

cplib() {
#copy and strip ARM library $1 and all symlinks to it
   $STRIP $1 -o $HOSTTOP/$1 && cplinks $1
}


cd $LIB && mkdir -p $HOSTTOP || exit 2
for lib in libc ld libm libnss_hesiod libnss_dns libnss_files libresolv libnsl \
           libcrypt libutil libdl
do
  cplib $lib-$LIBCVERS.so || exit 3
done
echo "Done."
