#!/bin/sh
#  first-time boot system configuration

echo "Making / writable for first-time boot configuration"
mount -oremount,rw / && {

  chmod u+s /bin/suidbox
  cd /home
  for user in *; do
    echo chown -R $user:users $user
  done

  rm $0  #this script will self-destruct...

}
