#!/bin/sh
#  first-time boot system configuration

echo "Making / writable for first-time boot configuration"
mount -oremount,rw / && {

  chmod u+s /bin/suidbox
  cd /home
  chown -R brent:users brent
  chown -R esp:users esp

  rm $0  #this script will self-destruct...

}
