#!/bin/sh
# unpack & patch rsync for arm-linux -- 11/11/19 brent@mbari.org

: ${rsync:=rsync-3.1.3}
rm -rf $rsync && 
tar xzf $rsync.tar.gz && 
#cat $rsync.patch | (cd $rsync && patch -p1) && 
cd $rsync || exit
configure --host=arm-softfloat-linux --disable-ipv6 --disable-locale \
  --with-included-zlib --with-included-popt &&
echo Done.
