#!/bin/sh
# unpack & patch rsync for arm-linux -- 11/9/21 brent@mbari.org
: ${ARMHOST:=arm-none-linux-gnueabi}
: ${rsync:=rsync-3.1.3}
rm -rf $rsync && 
tar xzf $rsync.tar.gz && 
cd $rsync || exit
configure --host=$ARMHOST --disable-ipv6 --disable-locale &&
echo Done.
