#!/bin/sh
# unpack & patch rsync for arm-linux -- 4/24/21 brent@mbari.org

: ${rsync:=rsync-3.1.3}
rm -rf $rsync && 
tar xzf $rsync.tar.gz && 
cd $rsync || exit
configure --host=arm-none-linux-gnueabi --disable-ipv6 --disable-locale &&
echo Done.
