#!/bin/bash -e
here=`dirname $0`
. $here/ltibEnv
: ${LOCALBIN=$HOSTTOP/usr/local/bin}
: ${SYSBIN=$HOSTTOP/usr/sbin}
cat <<EOS >&2
Augment root filesystem at $HOSTTOP for ESP application
  -- 4/6/16 brent@mbari.org
Usage:
  `basename $0` {root.tmp dir}
ltib root.tmp defaults to $HOSTTOP
EOS

mkdir -p $LOCALBIN

echo "  ===>  Building picocom  <==="
cd ~/linux/picocom
make CC=$ARMGCC/bin/gcc clean picocom
$STRIP -o $LOCALBIN/picocom picocom

echo "  ===>  Building snap  <==="
cd ~/misc/camera/starlight
make CC=$ARMGCC/bin/gcc clean ltib/snap
$STRIP -o $LOCALBIN/snap ltib/snap

echo "  ===>  Building timelimit  <==="
cd ~/misc/timelimit && armconfig && arminstall

echo "  ===>  Building sleepyCmd  <==="
cd ~/misc/sleepyCmd
make CC=$ARMGCC/bin/gcc clean ltib/sleepyCmd
$STRIP -o $SYSBIN/sleepyCmd ltib/sleepyCmd

echo "  ===>  Building holdopen  <==="
cd ~/misc/holdopen
make CC=$ARMGCC/bin/gcc clean ltib/holdopen
$STRIP -o $LOCALBIN/holdopen ltib/holdopen

echo "  ===>  Building suscript  <==="
cd ~/misc/suscript
make CC=$ARMGCC/bin/gcc clean ltib/suscript
$STRIP -o $HOSTTOP/usr/sbin/suscript ltib/suscript
chmod u+s $HOSTTOP/usr/sbin/suscript

echo "  ===>  Adding ssh->dropbear invocation script  <==="
cd ~/linux/esp/dropbear
install -m 755 ssh $HOSTTOP/usr/bin

echo "  ===>  Building dyndns  <==="
cd ~/linux/dyndns && armconfig && arminstall

echo "  ===>  Building wpa_supplicant  <==="
cd ~/linux/wpa_supplicant && armconfig && arminstall

echo "  ===>  Building slattach  <==="
cd ~/linux/esp/net-tools && armconfig && arminstall

cd ~/linux/esp && back=$PWD
for package in netdev ser2net ppp thttpd; do
  echo
  echo "  ===>  Building $package  <==="
  cd $package && armconfig && arminstall
  cd $back
done

echo
echo "  ===>  Building Ruby 1.8.7-mbari  <==="
cd ~/ruby/ruby-1.8.7-mbari && armconfig && arminstall
