#!/bin/bash -e
here=`dirname $0`
home=`eval echo ~${SUDO_USER}`
LTIB=$home/ltib
IMAGE=${2-$LTIB/rootfs.tmp}
[ -z $1 ] && {
  cat <<EOS >&2
Create new ltib root filesystem  -- 9/3/15 brent@mbari.org
Usage:
  `basename $0` newRootDir  {templateDir}
templateDir defaults to $IMAGE
EOS
  exit 2
}

[ -e $1 ] && {
  read -p "Remove existing destination directory: $1 (y/N)? " yn
  case $yn in
    Y|y|yes|YES|Yes)  sudo rm -rf $1;;
    *) exit 2;;
  esac
}

sudo sh -c "cp -a $IMAGE $1 && $here/replaceSkeleton $1"
[ -z "$BAREBONES" ] && $here/augmentSkeleton $1
echo "Setting owner of all files in $1 to root"
sudo sh -c "chown -R root:root $1 && cd $1/bin && chmod +s busybox mount umount"
