#!/bin/sh
#mksymlinks -- make symbolic links in directory $1

[ -z "$1" -o "$1" = "--help" ] && { cat <<EOS >&2
  Usage: `basename $0` base_directory {precmd}
Make symbolic links specified on stdin relative to specified base directory
Each line of stdin is of the form:
"symlink Name" -> "symlink Target"
Lines that lack the " -> " are ignored.  They may function as comments.
If the "symlink Target" is omitted, a directory called "symlink Name is created"
precmd is an optional preparation command.
Commonly, it is "rm -f" to remove any existing link beforehand
EOS
exit 1
}

mkdir -p $1 && cd $1 || exit 4

while read linkName arrow linkTarget; do
  [ "$arrow" = '->' ] && {
    if [ "$linkTarget" ]; then
      dir=`dirname $linkName`
      [ "$2" ] && eval $2 $linkName
      [ -d $dir ] || mkdir -p $dir || exit 2
      ln -s $linkTarget $linkName || exit 3
    else
      mkdir -p $linkName || exit 4
    fi
  }
done
