#!/bin/bash -e
#set -x
[ -z "$1" -o "$1" = "/" ] && {
  cat <<EOS >&2
Replace ltib skeleton in the rootfs the directory given as an argument
with the MBARI one for the ea31xx base board  -- 4/24/16 brent@mbari.org
EOS
  exit 2
}

dst=$1
here=`dirname $0`

etc=$1/etc
rcd=$etc/rc.d
rm $2 $rcd/rc.conf $rcd/rcS $rcd/rc.serial $rcd/rc.modules $rcd/init.d/* || {
  cat <<EOS >&2
Looks like $dst was not written by ltib or has already had its skeleton replaced
Invoke with -f as 2nd argument to force replacement anyway (this is dangerous!)
EOS
  exit 2
}
rm -rf $dst/home/* $dst/lost+found $dst/mnt/*  #remove ltib's users & mount pts


rm $dst/sbin/{halt,reboot,poweroff} `find $dst -name "*ip6t*"`
rm $dst/usr/bin/{ubi*,*jffs2*}  #remove support for ubi and jffs2 filesystems
rm $dst/usr/lib/{*.so.bak,*.so_orig,e2initrd*}
rm $dst/usr/sbin/tunelp
rm $dst/usr/bin/{unubi,pddcustomize,chkdupexe,*ftl_*,setarch,linux{32,64}}
rm $dst/usr/bin/{recv_image,rfd{dump,format},cytune}  #ubi + cyclades serial
rm $dst/usr/bin/gdbtui
rm $dst/usr/bin/oldfuser
rm $dst/etc/devfsd.conf
rm $dst/etc/udhcpd.conf
rm $dst/etc/sysctl.conf
rm $dst/etc/modprobe.conf.dist
rm -f $dst/bin/bashbug $dst/usr/bin/pstree.x11 $dst/etc/{issue.net,hosts}
chmod a-x $dst/etc/ltib-release

# remove all hotplug scripts and web server support
rm -f $dst/{sbin/hotplug,etc/resolv.conf}
rm -rf $dst/etc/hotplug* $dst/var/run
rm -rf $dst/var/www $dst/var/{lock,www,spool,mail,lib/locate,log/hotplug}

# record the initial state of the /var dir so new sd cards can be initialized
mv $dst/var $dst/etc &&
cp -a --no-preserve=ownership $here/rootfs/.  $dst &&
mksymlinks $dst < $here/symlinks &&
cd $dst/etc/var &&
mkdir -p log && chmod g-w log && cd log && {
      d=`date  -uIseconds` &&
      echo ${d%+*}UTC > birth &&
      echo "Image Built at  `date`"
}
