#!/bin/sh
#  Build updated wireless-compat kernel modules for updating ltibarm kernel
#   to restore support for rt2800usb and old atmel usb adapters
#  Binaries for from mod-init-tools 
#    should already be installed in ~/linux/ltib/bin
#    (configure and make in ltib/rpm/BUILD/mod-init-tools-3.* to generate these)
#
#  WARNINGS about missing crc_* symbols are expected
#
#  install all modules in /lib/modules/*/updates directory
#  Many wireless devices require firmware which can be simply copied 
#  from desktop linux into /lib/firmware (see also the firmware directory here)
# -- 9/1/15 brent@mbari.org
#
: ${compat:=compat-wireless-3.3-2-n}
: ${ltib:=~/ltib}
: ${ltibKernel:=$ltib/rpm/BUILD/linux}
: ${ltibModules:=`eval echo $ltib/rootfs.tmp/lib/modules/2.6.3*`}

[ -d $ltibKernel -a -d $ltibModules ] || {
  echo "-->  You must first prep and build the ltib kernel with cmds below <--"
  echo "$ cd $ltib"
  echo "$ ltib -p kernel -m prep
  echo "$ ltib -p kernel -m scbuild
  echo "$ ltib"
  exit 2
}
cd $compat &&
: ${compatModules:=~/ltib/rootfs.tmp} &&
: ${kmodPath:="KMODPATH_ARG=\"INSTALL_MOD_PATH=$compatModules\""} &&
ltibMake KLIB=$ltibModules KLIB_BUILD=$ltibKernel &&
ltibMake KLIB=$ltibModules KLIB_BUILD=$ltibKernel $kmodPath INSTALL_MOD_STRIP=1 install-modules
