#!/bin/sh
# unpack and patch vsftpd daemon for arm-linux -- 3/15/05 brent@mbari.org

: ${FTPDVERS:=vsftpd-1.2.2} 
rm -rf $FTPDVERS && tar xzf $FTPDVERS.tar.gz && cd $FTPDVERS &&
cp ../vsf_findlibs.sh . &&  
echo "Done."
