#!/bin/sh
#  first-time boot system configuration

echo "Making / writable for first-time boot configuration"
mount -oremount,rw / && {

  depmod -a

  cd /home
  for user in *; do
    chown -Rh $user:mbari $user
  done

  rm $0  #this script will self-destruct...

}
