#!/bin/sh
#  first-time boot system and users configuration

echo "Setting up users"
cd /home
for user in *; do
  chown -Rh $user:mbari $user
done

#so statd does not warn about running as root
cd /var/lib/nfs && chown -R nobody sm*

rm $0  #this script will self-destruct...
