#!/bin/sh
#Put ESP into a low power state from which it can restart
# later from radio page or alarm
#exit status:
#  0 if ready to powerdown
#  1 if powerdown preparations failed
#  2 if ready to powerdown, but modem did not sleep

export PATH=/usr/sbin:/sbin:/usr/bin:/bin

POWERDOWN=PowerDown
RUN=3
export recovering=yes  #don't clear /tmp or restart espserver

exec 2>/dev/console
exec >&2
#set -x

sync
/etc/rc.d/rc $POWERDOWN || {  #if power down fails
  /etc/rc.d/rc $RUN           #...try to recover
  exit 1
}
#coax modem into low power state
sleepModem <$modem >$modem || {
  echo -e "\nFailed to put modem to sleep!  Restarting..." >&2
  /etc/rc.d/rc $RUN  #...try to recover
  exit 2
}
echo
exec /etc/init.d/sysmount stop
