#!/bin/bash
# unpack and configure ppp for arm-linux -- 8/31/09 brent@mbari.org
: ${CFLAGS:="-Os -fomit-frame-pointer"}
: ${CXXFLAGS:=$CFLAGS}
: ${ARMGCC:=/arm}
: ${CC:=$ARMGCC/bin/gcc}
: ${LIBTOP:=${1-$ARMGCC}}
: ${PPPVERS:=ppp-2.4.2}
export CC CFLAGS CXXFLAGS
rm -rf $PPPVERS && tar xzf $PPPVERS.tar.gz && cd $PPPVERS &&
cp ../Makefile.pppd pppd/Makefile.linux &&
cp ../Makefile.rp-pppoe pppd/plugins/rp-pppoe/Makefile.linux &&
patch -p1 <../pppd-2.4.2-quickpid.patch &&
patch -p1 <../pppd-2.4.2-gateway.patch &&
cp patchlevel.h pppd-2.4.2/pppd &&
configure --host=arm-unknown-linux --prefix=$LIBTOP --includedir=$ARMGCC/include &&
echo "Next, run arminstall here"
