#!/bin/bash
# unpack and configure ppp for arm-linux -- 11/22/15 brent@mbari.org
: ${CFLAGS:="-Os -fomit-frame-pointer"}
: ${CXXFLAGS:=$CFLAGS}
: ${ARMGCC:=/arm}
: ${CC:=$ARMGCC/bin/gcc}
: ${LIBTOP:=${1-$ARMGCC/usr}}
: ${PPPVERS:=ppp-2.4.5}
: ${PPTPVERS:=pptp-1.7.2}
export CC CFLAGS CXXFLAGS
rm -rf $PPPVERS && tar xzf $PPPVERS.tar.gz &&
top=$PWD
cd $PPPVERS &&
patch -p1 <../$PPPVERS-makefile.patch &&
patch -p1 <../$PPPVERS-gateway.patch &&
patch -p1 <../$PPPVERS-keeppid.patch &&
cp ../$PPPVERS-patchlevel.h pppd/patchlevel.h &&
configure --host=arm-unknown-linux --prefix=$LIBTOP --includedir=$ARMGCC/include ||
exit 5

cd $top &&
rm -rf $PPTPVERS && tar zxf $PPTPVERS.tar.gz &&
cd $PPTPVERS &&
patch <../$PPTPVERS.patch &&
patch <../$PPTPVERS-quiet.patch &&
echo "Next, run arminstall here"
