#!/bin/sh
# build & install pppd for arm-linux -- 9/10/19 brent@mbari.org

: ${ARMGCC:=/arm}
: ${ARMSTRIP:=$ARMGCC/bin/strip}
: ${TARGETTOP:=${2-}}
: ${HOSTTOP:=${1-$HOME/armHost$TARGETTOP}}
: ${PPPprog:=pppd chat pppdump pppstats}
: ${COPTS:="-Os -fomit-frame-pointer"}
: ${INSTALL:="install --strip-program=$ARMSTRIP"}
: ${CC:=$ARMGCC/bin/gcc}
echo "Installing in $HOSTTOP"
echo "  for execution at $TARGETTOP on the ARM target"
top=$PWD
cd ${PPPVERS-ppp-2.4.5} || exit 2
mkdir -pm 755 $HOSTTOP/usr/sbin $HOSTTOP/usr/share/man/man8 &&
make -C pppd/plugins install \
  CC=$CC DESTDIR=$HOSTTOP/usr COPTS="$COPTS" INSTALL="$INSTALL" || exit 4
for prog in $PPPprog; do make -C $prog $prog install \
  CC=$CC DESTDIR=$HOSTTOP/usr COPTS="$COPTS" INSTALL="$INSTALL" || exit 4
done
rm -rf $HOSTTOP/usr/share/man $HOSTTOP/usr/sbin/pptpsetup

cd $top && cd ${PPTPVERS:=pptp-1.7.2} || exit 2
make CC=$CC OPTIMIZE="$COPTS" INSTALL="$INSTALL" RELEASE=-mbari6 DEBUG= &&
echo "Installing PPTP under $HOSTTOP" &&
$ARMSTRIP pptp &&
install -m 555 pptp $HOSTTOP/usr/sbin || exit 3
echo "Done."
