#!/bin/sh
# unpack and patch dnydns update daemon for arm-linux -- 2/2/12 brent@mbari.org

: ${inadyn:=inadyn}
rm -rf $inadyn && 
unzip $inadyn && 
cat $inadyn.patch | (cd $inadyn && patch -p1) && 
echo Done.
