#!/bin/sh
# build & install dnydns update daemon for arm-linux -- 2/10/12 brent@mbari.org

: ${ARMGCC:=/arm}
: ${ARMSTRIP:=$ARMGCC/bin/strip}
: ${TARGETTOP:=${2-usr/sbin}}
: ${HOSTTOP:=${1-$HOME/armHost}}
echo "Installing in $HOSTTOP"
echo "  for execution at $TARGETTOP on the ARM target"
TOP=$HOSTTOP/$TARGETTOP
prog=inadyn
cp $prog.conf $HOSTTOP/etc &&
cp reconnectVPN $TOP &&
cp dyndns $HOSTTOP/etc/init.d &&
chmod 600 $HOSTTOP/etc/$prog.conf &&
cd inadyn-1.98.1 || exit 2
make CC=/arm/bin/gcc || exit 1
mkdir -p $TOP || exit 4
$ARMSTRIP src/$prog -o $TOP/$prog || exit 3
echo "Done."
