#!/bin/sh
#if no args given, tries a next listed network interface to support the vpn
#any args are interpreted as a new list of interfaces (first is tried)
cell=ppp8
vpn=ppp9
priority=/etc/sysconfig/gateway.priority

if [ "$1" ] || read oldvpn phys < $priority && [ "$phys" ]; then
  set -- $phys
  badPhys=$1
  shift
  phys="$* $badPhys" 
else
  mkdir -p `dirname $priority`
  phys=$*
  : ${phys:=eth0 eth1 $cell}
  set -- $phys
fi
echo $vpn $phys > $priority
echo

echo "===> Selecting network interface $1 to support VPN on $vpn <==="
ifdown $vpn
ifdown $1
[ "$cell" -a "$1" != "$cell" ] && ifdown $cell
ifup $1
sleep 30
ifup $vpn
