#!/bin/sh
#don't attempt to bring up link if serial comms to modem just failed
[ -f /var/run/I2Cgate.reset ] || cell=ppp8   
#vpn=ppp9   
[ "$vpn" ] && ifdown $vpn
[ "$cell" ] && {
  ifdown $cell
  ifup $cell
  sleep 30
}
[ "$vpn" ] || exit 0
ifup $vpn
