#!/bin/sh
#Start/Stop ESP server
PATH=/usr/sbin:/sbin:/bin
user=esp
#pass some environment vars through to the espserver
env=
[ "${ESPcmdPort+set}" ] && env="ESPcmdPort=$ESPcmdPort"
[ "${ESPclient+set}" ] && env="$env ESPclient=$ESPclient"
[ "${ESPaxisPort+set}" ] && env="$env ESPaxisPort=$ESPaxisPort"
[ "${ESPcheckpoints+set}" ] && env="$env ESPcheckpoints=$ESPcheckpoints"
server="$env ~${user}/esp2/bin/espserver"

[ "$recovering" ] || exec su - $user -c "$server $@"
