#!/bin/sh
#Start/Stop ESP server writing ESP stdout log separate dated file
[ "$recovering" ] && exit

PATH=/usr/sbin:/sbin:/bin
user=esp
#pass some environment vars through to the espserver
env=
[ "${ESPcmdPort+set}" ] && env="ESPcmdPort=$ESPcmdPort"
[ "${ESPclient+set}" ] && env="$env ESPclient=$ESPclient"
[ "${ESPaxisPort+set}" ] && env="$env ESPaxisPort=$ESPaxisPort"
[ "${ESPcheckpoints+set}" ] && env="$env ESPcheckpoints=$ESPcheckpoints"
args="$env ${out:+out=$out} ~${user}/esp2/bin/espserver $@"

#-s /bin/sh below somehow suppresses shell's no job control warning
exec su - $user -s/bin/sh -c"$args"
