#!/bin/sh
#local configuration catch all

PATH=/usr/sbin:/sbin:/usr/bin:/bin
dropdir=/etc/dropbear
rcLocal=/etc/rc.local

case "$1" in
    start)
      # set-up to dump core to log dir
      coredir=/var/tmp/crash
      mkdir -p -m 1777 $coredir
      echo $coredir/%e-SIG%s.%p >/proc/sys/kernel/core_pattern
      rm -f /var/crash && ln -s tmp/crash /var/crash

      # ensure we have valid ssh server keys
      mkdir -p $dropdir
      for key in rsa ecdsa ed25519; do
        keyfn=dropbear_${key}_host_key
        if [ ! -e $dropdir/$keyfn ]; then
          echo "Generating $key key for the dropbear ssh server... "
          dropbearkey -t $key -f $dropdir/$keyfn >$dropdir/$keyfn.pub
        fi
      done

      mkdir -m600 -p /usr/share/empty  #for vsftpd

      [ -x $rcLocal ] && $rcLocal &
       ;;

    stop)
       :
       ;;

     *)
       echo "usage: local {start|stop}"
esac

