#!/bin/sh
#
# network	stop, restart, start, the networking
# subsequent args specify a list of interfaces

op="$1"
shift
[ -z "$1" ] && grep -q ^"/dev/root / nfs " /proc/mounts && {
  echo "Skipping network configuration so as not to disturb nfs root filesystem"
  exit 4
}
order=/etc/sysconfig/if-order
[ -r $order ] || exit 3
. $order
case "$op" in
   start)
      . /usr/share/ifupfn.sh
      if [ "$1" ]; then
	for dev; do
	  ifup $dev
	done
      else
        > /etc/resolv.conf
        > /etc/hosts
        for dev in $START; do
          ifup $dev
        done
        /lib/udev/catchup  #other interfaces start in parallel as discovered
      fi
;;
   stop)
     devs=$@
     [ "$devs" ] || {
       cd /sys/class/net
       devs=`for dev in $STOP; do echo $dev; done | awk '!seen[$0]++'`
     }
     for dev in $devs; do (
       defFn=/etc/sysconfig/ifcfg-$dev
       if [ -r "$defFn" ]; then
         . $defFn  #don't try to stop interfaces respawned by init process
         [ "${AUTOSTART#init}" != "$AUTOSTART" ] && continue
       fi
       ifdown $dev force
     ) done
   ;;

   restart)
	$0 stop	"$@"
	$0 start "$@"
	;;
   *)
   	echo "usage: start|stop|restart {interfaces}"
   ;;
esac
