#!/bin/sh
#mount or umount filesystems of the specified type
#and start logging to a file via nfs if /var/log is mounted
#default is to mount all nfs entries
#this can be overridden.  For example:
##  fstype=vfat service nfsmount start
#one can also select mounts of the specified type:
##  mount="#mbari" service nfsmount start
#mounts all (nfs) entries containing the string #mbari
#lines in /etc/fstab after any starting with #SUBNET <CIDR> ... are ignored
#if none of the specified subnets match that of our top priority IP address.

op=$1;shift
: ${fstype:=nfs}
: ${mount:="$@"}

. /usr/share/netutils.sh

# converts IPv4 as "A.B.C.D" to integer
# ip4int 192.168.0.1 => 3232235521
ip4int() {
  IFS=. read -r i j k l extra <<EOF
$1
EOF
  : ${i:=0} ${j:=0} ${k:=0} ${l:=0}
  echo $(( (i << 24) + (j << 16) + (k << 8) + l ))
}

topIface=`topIf` && topIP=`netIfIP $topIface` && myIP=`ip4int $topIP`
let "set32=(1<<32)-1"

subnetMatch() {
#return 0 if ip integer in first arg matches at least one of 
#CIDRs given in subsequent arg pairs
  ip=$1; shift
  unset mask
  for cidr do
    if [ "$mask" ]; then
      let "(ip ^ cidr) & mask" || return 0
      unset mask
    else
      mask=$cidr
    fi
  done
  return 1
}

allFsAuto() {
#outputs all $1 type mounts in /etc/fstab
# except those after a #SUBNET clause which excludes them
# optional $2 can be used to filter further
  fstype=$1
  grep "$2" /etc/fstab | {
    set --  #clear argv to mark subnet match
    while read device mntpt fs rest; do
      if [ "$myIP" -a "$device" = "#SUBNET" ]; then
        set -- 
        for cidr in $mntpt $fs $rest; do
          ip=${cidr%/*}
          bits=${cidr#*/}
          : ${bits:=32}
          set -- "$@" $(( (~set32>>bits) & set32 )) `ip4int $ip`
        done
        subnetMatch "$myIP" "$@" && set --
      elif [ "$fs" = "$fstype" -a -z "$1" ]; then
        echo $mntpt
      fi
    done
  }
}
    
mounted() {
#returns true if $1 is mounted, false if not, 2 if it does not exist
  realmnt=`realpath $1` || return 2
  cat /proc/mounts | 
    while read device mntpt rest; do
      [ "$realmnt" = "$mntpt" ] && return
    done
}

allFsMounts() {
#outputs all mounts of specified file system type $1 except those mounted on 
#the specified path $2
  cat /proc/mounts | 
    while read device mntpt fs rest; do
      [ "$fs" = "$1" -a "$mntpt" != "$2" ] && echo "$mntpt "
    done
}

chklog() {
#stop logging monentarily if mntpt is /var or /var/log
  act=$1
  mntpt=$2
  echo "  ${act}ing $mntpt " 
    case $mntpt in
      /var|/var/log)
        pidof syslogd >/dev/null && /etc/init.d/syslog stop >/dev/null
          $act $mntpt
        /etc/init.d/syslog start >/dev/null
      ;;
      *)  
        $act $mntpt
    esac
}

mnt() {
  echo "Mounting $fstype filesystems ..."
  [ "$mntpts" ] && {
    set $mntpts
    for mntpt do
      mounted $mntpt
      [ $? = 1 ] && chklog mount $mntpt
    done
  }
}

umnt() {
  echo "Unmounting $fstype filesystems ..."
  [ "$mntpts" ] && {
    set $mntpts
    for mntpt do
      mounted $mntpt && chklog umount $mntpt
    done
  }
}

case "$op" in
    start)
      mntpts=`allFsAuto $fstype $mount`
      [ -z "$mntpts" -a -n "$mount" ] && {
        echo "/etc/fstab contains no $fstype entries marked \"$mount\"!"
        exit 1
      }

      grep -qv '^[[:space:]]*#' /etc/resolv.conf || {
        echo "Missing Network -- skipping $fstype mounts"
        exit 1
      }
      mnt
       ;;
                         
    restart)
      mntpts=`allFsAuto $fstype $mount`
      umnt
      mnt
       ;;
       
    stop)
      if [ "$mount" ]; then
        mntpts=`allFsAuto $fstype $mount`
        umnt
      else
        nonRootNFS=`allFsMounts $fstype /`
        if [ -n "$nonRootNFS" ]; then
          echo "Unmounting all $fstype filesystems"
          umount -l $nonRootNFS 2>&1 | grep -v ": not mounted$"
        fi
      fi
       ;;
       
    *)
       echo "usage: start|restart|stop"
       ;;
esac
