#!/bin/sh
PATH=$PATH:/sbin:/bin
statd=/var/run/rpc.statd.pid
OPTIONS=""

case "$1" in
    start)
       echo "Starting portmap..."
       /sbin/portmap $OPTIONS
       ;;

    stop)
       statdpid=`cat $statd` 2>/dev/null && [ "$statdpid" ] && kill "$statdpid"
       rm -f $statd
       ;;

     *)
       echo "usage: portmap {start|stop}"
       ;;
esac
