#!/bin/sh
: ${rebootOptions:=$2}

case "$1" in
    start)
       echo "Rebooting ..."
       /bin/busybox reboot $rebootOptions
       ;;
                         
     *)
       echo "usage: start"
       ;;
esac
