#!/bin/sh
# save and restore RTC, or fake it if no hardware available

birth=/var/log/birth  #birthdate timestamp
log=/var/log/messages

show() {
  [ "$quiet" ] || echo "$@"
}

while [ -c /dev/rtc0 -a -x /sbin/hwclock ]; do
  RTCmode=-u  #RTC keeps time in:  -u for UTC, -l for local time

  case "$1" in
    start)
      /sbin/hwclock -s $RTCmode || break
      year=`date +%Y` && [ "$year" -le 2002 ] && { #assume dates < 2003 bogus
        show "Clock failure -- likely dead battery" >&2
        break
      }
      show -n "Set system clock to:  "
      date
       ;;

    stop)
      show -n "Set Real-Time clock to:  "
      date
      /sbin/hwclock -w $RTCmode
      date  -uIseconds >$birth
      touch $log
       ;;

    *)
      break
       ;;
  esac

  exit
done

case "$1" in
  start)
    logStamp=`date -r $log +%s` &&
    date -D%s $logStamp >/dev/null &&
    show -n "Restored clock to time of last log update:  " ||
      show -n "Failed to restore clock:  "
    date
     ;;

  stop)
    date  -uIseconds >$birth &&
    touch $log
    show -n "Saved system clock at `date`"
     ;;

  *)
     echo "usage: start|stop"
     echo "on start:  restore the system clock from RTC"
     echo "on stop:   save the system clock to RTC"
     ;;
esac
