#!/bin/sh
# save and restore RTC, or fake it if no hardware available

if [ -c /dev/rtc0 -a -x /sbin/hwclock ]; then
  RTCmode=-u  #RTC keeps time in:  -u for UTC, -l for local time

  case "$1" in
    start)
      echo -n "Set system clock to:  "
      /sbin/hwclock -s $RTCmode
      date
       ;;

    stop)
      echo -n "Set Real-Time clock to:  "
      date
      /sbin/hwclock -w $RTCmode
       ;;

    *)
       echo "usage: start|stop"
       echo "on start:  set the system clock from the hardware clock"
       echo "on stop:   set the hardware clock from the system clock"
       ;;
  esac

else

  birth=/var/log/birth
  case "$1" in
    start)
      if [ -r $birth ]; then
        d=`cat $birth` &&
        inputDate=`echo ${d%UTC} | tr T ' '` &&
        date  -us"$inputDate" >/dev/null
      fi
      date
       ;;

    stop)
      date  -uIseconds >$birth &&
      echo "Saved system clock at `date`"
       ;;

    *)
       echo "usage: start|stop"
       echo "on start:  restore the system clock"
       echo "on stop:   save the system clock"
       ;;
  esac
fi
:
