#!/bin/sh
#Choose between satellite and cell comms based upon which are powered
#Yepkit hub powers up with all ports powered
#So, this only chooses satellite only if it is powered and cell is not.

case "$1" in
  start)
    power sat | grep -qi "off$"
    satOff=$?

    #power off sat if cell is powered
    if power cell | grep -qi "ON$"; then
      [ $satOff != 0 ] && power sat off
      exit
    else #bring up satellite link if it is to only powered
      if [ $satOff != 0 ]; then
        echo Starting certus...
        (sleep 30; ifup certus)&
      else #start with cell if neither powered
        power cell on
      fi
    fi
     ;;

  *)
     echo "usage: start"
     echo "on start:  start cellular or satellite comms"
esac
