#!/bin/sh
#sychronize real-time with Iridium network and log geo location

PATH=/usr/sbin:/sbin:/usr/bin:/bin

case "$1" in
  start|"")
    echo "Syncing time with Iridium network"
    detachIridium && sysTime=`iridiumTime` && {
      date -us "$sysTime"
      geo=`iridiumLocation` &&
      logger -t IridiumLocation -p warning -- "$geo"
    }
;;
  stop)
;;
  *)
     echo "usage: `basename $0` {start|stop}"
esac
