#!/bin/sh
#sychronize real-time with Iridium network

PATH=/usr/sbin:/sbin:/usr/bin:/bin

case "$1" in
    start|"")
      echo "Syncing time with Iridium network"
      sysTime=`iridiumTime` && date -us "$sysTime"
       ;;

    stop)
       ;;

     *)
       echo "usage: `basename $0` {start|stop}"
       ;;
esac
