#!/bin/sh
#sychronize real-time with network

ntpserver=us.pool.ntp.org
rdateserver=bufflehead

PATH=/usr/sbin:/sbin:/bin

OPTIONS=""

case "$1" in
    start|"")
      if grep -qv '^[[:space:]]*#' /etc/resolv.conf; then
        if [ -n $ntpserver ] && timelimit -t30 -T3 ntpclient -s -h $ntpserver >/dev/null; then
          echo "Clock sycn'd with $ntpserver at `date` via ntp"
          exit 0
        fi
        if [ -n $rdateserver ] && rdate $rdateserver; then 
          echo "Clock sycn'd with $rdateserver via rdate"
          exit 0
        fi
      fi
      echo "Network unavailable:  Local time is `date`"
       ;;

    stop)
       ;;

     *)
       echo "usage: synctime {start|stop}"
       ;;
esac
