#!/bin/sh
#sychronize real-time with network

ntpserver=us.pool.ntp.org
rdateserver=bufflehead

PATH=/usr/sbin:/sbin:/bin

OPTIONS=""

case "$1" in
    start|"")
      if grep -qv '^[[:space:]]*#' /etc/resolv.conf; then
        if [ "$ntpserver" ] &&
           timelimit -t8 -T3 ntpclient -s -h $ntpserver >/dev/null; then
          echo -n "NTP sycn'd with $ntpserver at "
          quiet=1 exec /etc/init.d/rtc stop
        fi
        if [ "$rdateserver" ] && timelimit -t5 -T3 rdate $rdateserver; then
          echo -n "rdate sycn'd with $rdateserver at "
          quiet=1 exec /etc/init.d/rtc stop
        fi
      fi
      echo "Network unavailable:  Local time is `date`"
       ;;

    stop)
       ;;

     *)
       echo "usage: synctime {start|stop}"
       ;;
esac
