#!/bin/sh
PATH=$PATH:/sbin:/bin

case "$1" in
    start)
        echo "" > /proc/sys/kernel/hotplug

        mount -n -o mode=0755 -t tmpfs tmpfs /dev

        # Create static device nodes in /dev
        mknod /dev/console c 5 1
        mknod /dev/null c 1 3

        echo "Starting the hotplug events dispatcher udevd"
        udevd --daemon

        echo "Synthesizing initial hotplug events"
        udevtrigger
        udevsettle --timeout=30

        mkdir /dev/pts  /dev/shm
        ;;
    stop)
        ;;
    reload|restart)
        udevcontrol --reload_rules
        ;;
    *)
        echo "Usage: /etc/rc.d/init.d/udev {start|stop|reload|restart}"
        echo
        exit 1
        ;;
esac

:
