#!/bin/sh
prog=`basename $0`
initial=
interval=600

case "$1" in -[0-9][0-9]*)
  interval=${1#-}
  case "$2" in -[0-9][0-9]*)
    initial=$interval
    interval=${2#-}
    shift
  esac
  shift
esac
: ${initial:=$interval}

case "$1" in
  '' | -*) cat >&2 <<END
Monitor specified wiregard interface -- 2/19/25 brent@mbari.org
Runs specified command whenever wiregard handshake delayed too long
Usage:
  $prog {-maxBeforeFirst} {-maxInterval} [wgNetIface] {command plus arguments}
where:
  maxInterval = maximum number of seconds between handshakes
  maxBeforeFirst = maximum number of seconds allowed for initial handshake
    (only if parameter appears immediately before -maxInterval)
Examples:
  $prog -900 wg2shore       #allow up to 15 minutes between handshakes
  $prog -120 -600 wg2shore  #require 1st in 2 min, 10 min between subsequent
If -maxInterval omitted, allow up to $interval seconds between handshakes
END
  exit 2
esac
iface="$1"
shift

: ${traceFn:=/var/run/trace/$prog}
[ -w $traceFn ] && {
  { date; echo "$@"; env; } >>$traceFn
  exec 2>>$traceFn
  set -x
}

#first, kill any running watch on this interface
pidFn=/var/run/$iface-$prog.pid
[ -s "$pidFn" ] && oldWatch=`cat $pidFn` &&
  kill $oldWatch 2>/dev/null && sleep 1
echo $$ >$pidFn

trap "rm $pidFn" EXIT
trap "exit 130" TERM INT QUIT HUP PIPE

timeOfLastHandshake() {
# 1st arg is a wiregard network interface
  lastHandshake=`wg show $1 latest-handshakes` || return
  echo "$lastHandshake" | {
    read pubKey time junk
    echo $time
  }
}

timeNow() {
  date +%s
}

now=`timeNow`
delay=$initial
handshakeTime=$now
while sleep $((handshakeTime + delay - now)); do
  delay=$interval
  now=`timeNow`
  handshakeTime=`timeOfLastHandshake $iface` && {
    [ "$handshakeTime" -a $((now - handshakeTime)) -lt $interval ] &&
      continue
  }
  logger -t $prog -p daemon.warning "restarting $iface + $@"
  ifdown $iface
  eval "$@"
  ifup $iface
  delay=$initial
  handshakeTime=$now
done
