#!/bin/sh
# build & install ifplugd-0.28 for arm-linux -- 12/1/05 brent@mbari.org

: ${ARMGCC:=/arm}
: ${ARMSTRIP:=$ARMGCC/bin/strip}
: ${TARGETTOP:=${2-/usr/sbin}}
: ${HOSTTOP:=${1-$HOME/armHost$TARGETTOP}}
echo "Installing in $HOSTTOP"
echo "  for execution at $TARGETTOP on the ARM target"
mkdir -p $ARMGCC/etc/init.d &&
cd ${IFPLUGVERS-ifplugd-0.28} || exit 2
make sysconfdir=/etc &&
make install &&
for tool in ifplugd; do #ifplugstatus
  $ARMSTRIP -o$HOSTTOP/$tool $ARMGCC/$TARGETTOP/$tool || exit 4
done
echo "Done."
