#!/bin/sh
: ${haltOptions:=$2}

case "$1" in
    start)
       echo "Halting..."
       /sbin/crash/halt $haltOptions
       ;;
                         
     *)
       echo "usage: start"
       ;;
esac
