#!/bin/sh
#
# network	stop, restart, start, the networking
# subsequent args specify a list of interfaces

op="$1"
shift
case "$op" in 
   start)
      . /usr/share/ifupfn.sh
      if [ "$1" ]; then
	for dev; do
          unset AUTOSTART DEVICE BOOTPROTO IPADDR NETMASK BROADCAST DHCPNAME
          unset NETWORK GATEWAY NSprepCmd
	  . /etc/sysconfig/ifcfg-$dev
          ifup_function
        done
      else
        > /etc/resolv.conf
        > /etc/hosts
        fnspec='/etc/sysconfig/ifcfg-*'
        fns=`echo $fnspec`
        [ "$fns" = "$fnspec" ] && exit  #no network configs found
	for defFn in $fns; do
          unset AUTOSTART DEVICE BOOTPROTO IPADDR NETMASK BROADCAST DHCPNAME
          unset NETWORK GATEWAY NSprepCmd
          . $defFn
          ifup_function yes
        done
      fi
   ;;
   stop)
      devs=$@
      [ "$devs" ] || {
        pppSpec='/var/run/ppp[0-9]*.pid'
        pidfns=`echo $pppSpec`
set -f
        if [ $pidfns != $pppSpec ]; then
          for pidFn in $pidfns; do  #stop ppp links that are "down"
            ppp=`basename $pidFn`
            devs="$devs ${ppp%.pid}"
          done
        fi  #now add in everything but ppp interfaces
set +f
        devs="$devs `grep -v '^ *ppp[0-9][0-9]*:' /proc/net/dev |
              sed -ne'/:/p' | cut -d: -f1`"
      }
      for dev in $devs; do
        defFn=/etc/sysconfig/ifcfg-$dev
        if [ -r "$defFn" ]; then
          . $defFn  #don't try to stop interfaces respawned by init process
          [ "$AUTOSTART" = "init" ] && continue
        fi
        ifdown $dev
      done
   ;;

   restart)
	$0 stop	"$@"
	$0 start "$@"
	;;
   *)
   	echo "usage: start|stop|restart {interfaces}"
   ;;
esac
