#!/bin/sh
#
# network	stop, restart, start, the networking
# subsequent args specify a list of interfaces

op="$1"
shift
[ -z "$1" ] && grep -q ^"/dev/root / nfs " /proc/mounts && {
  echo "Skipping network configuration so as not to disturb nfs root filesystem"
  exit 4
}
case "$op" in 
   start)
      . /usr/share/ifupfn.sh
      if [ "$1" ]; then
	for dev; do
          unset IFNAME BOOTPROTO IPADDR NETMASK BROADCAST DHCPNAME
          unset NETWORK GATEWAY MTU AUTOSTART
          unset resolv_conf hosts ifPrep ifPost
	  . /etc/sysconfig/ifcfg-$dev
          ifup_function
        done
      else
        > /etc/resolv.conf
        > /etc/hosts
        fnspec='/etc/sysconfig/ifcfg-*'
        fns=`echo $fnspec`
        [ "$fns" = "$fnspec" ] && exit  #no network configs found
	for defFn in $fns; do
          unset IFNAME BOOTPROTO IPADDR NETMASK BROADCAST DHCPNAME
          unset NETWORK GATEWAY MTU AUTOSTART
          unset resolv_conf hosts ifPrep ifPost
          . $defFn
          ifup_function 'yes|Y|Yes|YES'
        done
      fi
      # netowrking stack tweaks
 #     echo 1 > /proc/sys/net/ipv4/ip_forward &&
 #     echo Packet forwarding enabled

   ;;
   stop)
      devs=$@
      [ "$devs" ] || {
        pppSpec='/var/run/ppp[0-9]*.pid'
        pidfns=`echo $pppSpec`
set -f
        if [ "$pidfns" != "$pppSpec" ]; then
          for pidFn in $pidfns; do  #stop ppp links that are "down"
            ppp=`basename $pidFn`
            devs="$devs ${ppp%.pid}"
          done
        fi  #now add in everything but ppp interfaces
set +f
        devs="$devs `grep -v '^ *ppp[0-9][0-9]*:' /proc/net/dev |
              sed -ne'/:/p' | cut -d: -f1`"
      }
      for dev in $devs; do
        unset IFNAME BOOTPROTO IPADDR NETMASK BROADCAST DHCPNAME
        unset NETWORK GATEWAY MTU AUTOSTART resolv_conf hosts
        defFn=/etc/sysconfig/ifcfg-$dev
        if [ -r "$defFn" ]; then
          . $defFn  #don't try to stop interfaces respawned by init process
           #if autostart mode missing or it starts with init, skip dev up check
          [ -z "$AUTOSTART" -o "${AUTOSTART#init}" != "$AUTOSTART" ] && continue
        fi
        ifdown $dev force
      done
   ;;

   restart)
	$0 stop	"$@"
	$0 start "$@"
	;;
   *)
   	echo "usage: start|stop|restart {interfaces}"
   ;;
esac
