#!/bin/sh
: ${poweroffOptions:=$2}

case "$1" in
    start)
       echo "Powering Off..."
       /sbin/crash/poweroff $poweroffOptions
       ;;
                         
     *)
       echo "usage: start"
       ;;
esac
