#!/bin/sh
#
# USB subsystem start
#  /sbin/hotplug now autoloads commonly used usb drivers

: ${USBHOST=usb-ohci-ep93xx}

case "$1" in 
   start)
      modprobe $USBHOST      
   ;;
   *)
   	echo "usage: start"
esac
   
	
