#!/bin/sh
#
# USB subsystem start
#  also loads commonly used USB modules

: ${USBHOST=usb-ohci-ep93xx}

case "$1" in 
   start)
      modprobe $USBHOST &&
      modprobe sx_usb && {    #preload starlight CCD camera driver
        mknod -m0666 /dev/ccda  c 127 0
        mknod -m0666 /dev/ccda1 c 127 16
        mknod -m0666 /dev/ccda2 c 127 32
        mknod -m0666 /dev/ccdA  c 127 128
        mknod -m0666 /dev/ccdA1 c 127 144
        mknod -m0666 /dev/ccdA2 c 127 160
        mknod -m0666 /dev/ccdb  c 127 1
        mknod -m0666 /dev/ccdb1 c 127 17
        mknod -m0666 /dev/ccdb2 c 127 33
        mknod -m0666 /dev/ccdB  c 127 129
        mknod -m0666 /dev/ccdB1 c 127 145
        mknod -m0666 /dev/ccdB2 c 127 161
      } 2>/dev/null  #don't complain if nodes already exist
      
   ;;
   *)
   	echo "usage: start"
   ;;
esac
   
	
