#!/bin/bash
# unpack, patch and configure dropbear-git build for arm-linux 
#  -- 7/30/19 brent@mbari.org
: ${CFLAGS:=-O2}
: ${CXXFLAGS:=$CFLAGS}
: ${ARMGCC:=/arm}
: ${CC:=$ARMGCC/bin/gcc}
: ${LIBTOP:=${1-$ARMGCC/usr}}
: ${DBVERS:=dropbear-git}
export CC CFLAGS CXXFLAGS
unset zlib
[ "$ARMPREFIX" ] && zlib="--with-zlib=$ARMPREFIX"
cd $DBVERS || {
  git clone https://github.com/mkj/dropbear.git $DBVERS &&
  cd $DBVERS || exit $?
}
git reset --hard &&
git clean -dxf &&
git checkout DROPBEAR_2019.78 &&
patch < ../dropbear-mbari2.patch &&
autoconf && autoheader &&
configure --host=arm-unknown-linux $zlib \
 --disable-lastlog --disable-utmp --disable-utmpx \
 --disable-wtmp --disable-wtmpx --disable-pututline --disable-pututxline &&
echo "Next, run arminstall here"
