#!/bin/bash
# unpack, patch and configure dropbear-git build for arm-linux 
#  -- 11/8/21 brent@mbari.org
TOP=`pwd`
: ${CFLAGS:=-O2}
: ${CXXFLAGS:=$CFLAGS}
: ${ARMGCC:=/arm}
: ${CC:=$ARMGCC/bin/gcc}
: ${LIBTOP:=${1-$ARMGCC/usr}}
: ${DBVERS:=dropbear-git}
export CC CFLAGS CXXFLAGS
unset zlib
[ "$ARMPREFIX" ] && zlib="--with-zlib=$ARMPREFIX"
cd $DBVERS || {
  git clone https://github.com/brentr/dropbear.git $DBVERS &&
  cd $DBVERS || exit $?
}
git reset --hard &&
git clean -dxf &&
git checkout mbari &&
cp $TOP/localoptions.h . &&
autoconf && autoheader &&
configure --host=arm-unknown-linux $zlib \
 --disable-lastlog --disable-utmp --disable-utmpx --disable-harden \
 --disable-wtmp --disable-wtmpx --disable-pututline --disable-pututxline &&
echo "Next, run arminstall here"
