#!/bin/bash
# unpack, patch and configure dropbear-0.45 build for arm-linux 
#  -- 3/15/05 brent@mbari.org
: ${CFLAGS:=-Os}
: ${CXXFLAGS:=$CFLAGS}
: ${ARMGCC:=/arm}
: ${CC:=$ARMGCC/bin/gcc}
: ${LIBTOP:=${1-$ARMGCC/usr}}
: ${DBVERS:=dropbear-0.45}
export CC CFLAGS CXXFLAGS
tar xzf $DBVERS.tar.gz && cd $DBVERS && 
patch < ../restore-all-fd.patch &&
cp -f ../options.embedded options.h && ac_cv_func_logout=no \
configure --host=arm-unknown-linux --prefix=$LIBTOP \
 --disable-lastlog --disable-utmp --disable-utmpx \
 --disable-wtmp --disable-wtmpx --disable-pututline --disable-pututxline &&
echo "Next, run arminstall here"
