#!/bin/sh
# build & install dropbear-0.45 for arm-linux -- 3/15/05 brent@mbari.org

: ${ARMGCC:=/arm}
: ${ARMSTRIP:=$ARMGCC/bin/strip}
: ${TARGETTOP:=${2-/usr}}
: ${HOSTTOP:=${1-$HOME/armHost$TARGETTOP}}
echo "Installing in $HOSTTOP"
echo "  for execution at $TARGETTOP on the ARM target"
cd ${DBVERS-dropbear-0.45} || exit 2
make PROGRAMS="dropbear dbclient dropbearkey scp" MULTI=1 || exit 1
set -x
install -d -m 755 $HOSTTOP/bin $HOSTTOP/sbin &&
install -m 755 dropbearmulti dbclient dropbearkey scp $HOSTTOP/bin &&
cd $HOSTTOP/bin &&
$ARMSTRIP dropbearmulti &&
rm -f ../sbin/dropbear dbclient dropbearkey scp &&
ln -s $TARGETTOP/bin/dropbearmulti ../sbin/dropbear &&
ln -s dropbearmulti dbclient &&
ln -s dropbearmulti dropbearkey &&
ln -s dropbearmulti scp &&
echo "Done."
