#!/bin/bash
# unpack & configure psmisc build for arm-linux -- 7/24/12 brent@mbari.org
: ${PSMISCVERS:=psmisc-22.3}
: ${CFLAGS:=-Os -fomit-frame-pointer}
: ${CXXFLAGS:=$CFLAGS}
: ${ARMGCC:=/arm}
: ${CC:=$ARMGCC/bin/gcc}
: ${LIBTOP:=${1-$ARMGCC/usr}}
export CFLAGS CXXFLAGS
top=$PWD
rm -rf $PSMISCVERS && tar zxf ${PSMISCVERS}[-.]tar.gz 2>/dev/null || exit $?
cd $PSMISCVERS
ac_cv_func_malloc_0_nonnull=yes ac_cv_func_realloc_0_nonnull=yes \
  configure --disable-ipv6 --disable-nls --host=arm-softfloat-linux &&
echo "Now, run arminstall"
