#!/bin/sh
# build & install just the fuser command of psmisc for arm-linux
# -- 5/8/12 brent@mbari.org

: ${PSMISCVERS:=psmisc-22.16}
: ${ARMGCC:=/arm}
: ${ARMSTRIP:=$ARMGCC/bin/strip}
: ${TARGETTOP:=${2-/usr/bin}}
: ${HOSTTOP:=${1-$HOME/armHost$TARGETTOP}}

echo "Installing in $HOSTTOP"
echo "  for execution at $TARGETTOP on the ARM target"
cd $PSMISCVERS || exit 2
make
echo "errors are expected due to lack of curses library"

for tool in fuser; do
  $ARMSTRIP src/$tool -o $HOSTTOP/$tool
done
echo "Done."
