#!/bin/sh
# unpack and patch thttpd daemon for arm-linux -- 3/24/20 brent@mbari.org

: ${HTTPDVERS:=thttpd-2.25b}
: ${CFLAGS:=-Os -fomit-frame-pointer}
: ${ARMGCC:=/arm}
: ${CC:=$ARMGCC/bin/gcc}
export CC CFLAGS
rm -rf $HTTPDVERS && tar xzf $HTTPDVERS.tar.gz && cd $HTTPDVERS &&
patch -p1 <../$HTTPDVERS.patch &&
configure --host=$ARMHOST &&  
echo "Done."
