#!/bin/sh
# unpack and patch vsftpd daemon for arm-linux -- 3/15/05 brent@mbari.org

: ${HTTPDVERS:=thttpd-2.25b}
rm -rf $HTTPDVERS && tar xzf $HTTPDVERS.tar.gz && cd $HTTPDVERS &&
CC=/arm/bin/gcc configure --host=arm-softfloat-linux &&  
echo "Done."
