#!/bin/sh
# unpack and patch vsftpd daemon for arm-linux -- 9/1/15 brent@mbari.org

: ${HTTPDVERS:=thttpd-2.25b}
: ${CFLAGS:=-Os -fomit-frame-pointer}
: ${ARMGCC:=/arm}
: ${CC:=$ARMGCC/bin/gcc}
export CC CFLAGS
rm -rf $HTTPDVERS && tar xzf $HTTPDVERS.tar.gz && cd $HTTPDVERS &&
configure --host=arm-softfloat-linux &&  
echo "Done."
