#!/bin/sh
# build & install thttpd daemon for arm-linux -- 3/24/20 brent@mbari.org

: ${ARMGCC:=/arm}
: ${ARMSTRIP:=$ARMGCC/bin/strip}
: ${TARGETTOP:=${2-usr/sbin}}
: ${HOSTTOP:=${1-$HOME/armHost$TARGETTOP}}
: ${CFLAGS:=-Os -fomit-frame-pointer}
: ${CC:=$ARMGCC/bin/gcc}
export CC CFLAGS
echo "Installing in $HOSTTOP"
echo "  for execution at $TARGETTOP on the ARM target"
install -Dm 755 httpd $HOSTTOP/etc/init.d &&
cd ${HTTPDVERS-thttpd-2.25b} || exit 2
make CCOPT="$CFLAGS" && $ARMSTRIP thttpd &&
install -Dm 755 thttpd $HOSTTOP/usr/sbin/thttpd &&
echo "Done."
