#!/bin/sh
# unpack & patch busybox for arm-linux -- 3/15/05 brent@mbari.org
: ${BBVERS:=busybox-1.00}
rm -rf $BBVERS && tar xjf $BBVERS.tar.bz2 && cd $BBVERS &&
patch -p1 <../busybox-1.00esp.patch &&
echo "Done."

