#!/bin/sh
# executed after disconnecting the ppp interface.

. /usr/share/netutils.sh

bkgfn="/var/run/$IFNAME-bkg.pid"
bkgpid=`cat $bkgfn` && {
  rm $bkgfn
  [ "$bkgpid" ] && kill $bkgpid
}

ipDown $IFNAME
