#!/bin/sh
# executed after disconnecting the ppp interface.
#$IFNAME is not assigned on retries, but $1 is.
export PPP_IFACE="$1"

. /usr/share/netutils.sh
configfn=/etc/sysconfig/ifcfg-$PPP_IFACE
[ -r $configfn ] && . $configfn

tracefn=/tmp/ip-down.trace
if [ -w $tracefn ]; then
  (date; echo "$@"; env) >>$tracefn
  exec 2>>$tracefn
  set -x
fi

type pppDown >/dev/null 2>&1 && pppDown

ipDown $PPP_IFACE
