#!/bin/sh
# executed after connecting the ppp interface.
[ "$5" ] || exit 1
PATH=/usr/sbin:/sbin:/usr/bin:/bin
PPP_TTY="$2"
PPP_SPEED="$3"
PPP_LOCAL="$4"
PPP_REMOTE="$5"
PPP_IPPARAM="$6"
export PPP_TTY PPP_SPEED PPP_LOCAL PPP_REMOTE PPP_IPPARAM PATH

pppUp() {
  :  #before ppp interface comes up
}
. /usr/share/netutils.sh
ifCfg $1

pppUp

unset domain gateway
[ "$DEFAULTROUTE" ] && gateway=" $IPREMOTE"

#if PEERNAME is prefixed with a dot, change our own hostname to it
if [ -n "$PEERNAME" ]; then
  IFS=.
  set $PEERNAME
  IFS=
  if [ -z "$1" -a -n "$2" ]; then  #there was a leading dot!
    host=$2
#    [ -f $oldHostname ] || hostname >$oldHostname
    if [ $# -gt 2 ]; then
      domain=$3
      shift 3
      for component; do
        domain=$domain.$component
      done
    fi
#      hostname $host  #disable changing hostname
  fi
fi

[ "$USEPEERDNS" ] && {
  resolv_conf() {
    echo "search `searchDomains $domain`"
    for ip in $DNS1 $DNS2 ; do
      echo "nameserver $ip"
    done
  }
}

gateUp $IFNAME $gateway && hostsUp $IFNAME &&
  [ "$VPN" ] && vpnUp "$VPN" $IFNAME
gateUpdated
