#!/bin/bash
#  This script assumes that empty, formatted partitions
#labeled BOOT, ROOT and HOME have been
#created on the main disk drive to receive the Linux system image.
#  revised:  1/24/11 brent@mbari.org
#
set -e  #abort on error

cd `dirname $0`
archive=`pwd`

mount LABEL=BOOT /boot
mount LABEL=ROOT /mnt/root
mount LABEL=HOME /mnt/home

xtract="--numeric-owner -zxf"

echo "Configuring BOOT partition"
cd /boot
tar $xtract $archive/boot.tgz .
lilo -C lilo.conf

echo "Populating ROOT partition"
cd /mnt/root
tar $xtract $archive/root.tgz .
mkdir -p media  #forgot this on root.tgz
powerbtn=$archive/powerbtn-acpi-support.sh
[ -r $powerbtn ] && cp -af $powerbtn etc/acpi
[ "$1" ] && echo "$1" > etc/hostname 

echo "Populating HOME partition"
cd /mnt/home
tar $xtract $archive/home.tgz .

echo "Linux successfully loaded on host $1"
