#!/bin/sh
# build & install portmap daemon for arm-linux -- 1/25/06 brent@mbari.org

: ${ARMGCC:=/arm}
: ${ARMSTRIP:=$ARMGCC/bin/strip}
: ${TARGETTOP:=${2-/usr/sbin}}
: ${HOSTTOP:=${1-$HOME/armHost$TARGETTOP}}
: ${UTIL:=${3-flash_eraseall}}
baseUtil=`basename $UTIL`
echo "Installing $baseUtil in $HOSTTOP"
echo "  for execution at $TARGETTOP on the ARM target"
cd ${MTDDIR-mtd-2004} || exit 2
make CROSS=$ARMGCC/bin/ $UTIL &&
$ARMSTRIP $UTIL &&
install -Dm 755 $UTIL $HOSTTOP/$baseUtil || exit 1
echo "Done."
