#!/bin/sh
#when "RING" received on /dev/modem, bring up specified network interface
#1st optional argument is initial delay
#2nd optional argument is interface to bring up
#3rd optional argument is serial port to monitor for RING
#any remaining optional arguments are passed thru to stty
export PATH=/usr/sbin:/sbin:/usr/bin:/bin

sleep ${1-20}
iface=${2-iridium}
eval "exec <${3-/dev/modem}"
shift 3
[ "$1" ] || set -- -cooked 115200
stty "$@"
flush
while read line; do
  [ "$line" = RING$'\r' ] && exec ifup $iface </dev/null
done
