#!/bin/sh
self=`basename $0`
tmpMnt=/var/lock/${self}_root.$$
dev=dev/.dev.tgz  #normal /dev for late or disabled coldplug
devMin=dev/.dev-minimal.tgz  #minimal /dev for early coldplug
rcDir=/etc/rc.d/rc3.d
inittab=/etc/inittab

mountRoot() {
  [ "`mntPt /dev`" = /dev ] || {
    echo "/dev is mounted properly" >&2
    exit 4
  }
  trap "umountRoot" EXIT
  mkdir $tmpMnt && mount --bind / $tmpMnt || exit
}

umountRoot() {
  umount $tmpMnt
  rmdir $tmpMnt
}

mntPt() {
#output the mount point of the filesystem containing given path
  [ -e "$1" ] || return
  /bin/df "$1" | tail -n1 | (
    read -r fsTyp sz used aval use mntpt other; echo $mntpt
  )
}

updateInittab() {
  sed -i $@ $inittab
}

updateRC() {
  mkdir -p $rcDir/$2
  mv $rcDir/$1 $rcDir/$2 2>/dev/null
}

case "$1" in
 early|--early)
  mountRoot
  [ -e $tmpMnt/$dev -a -e $tmpMnt/$devMin ] && {
    ln -sf `basename $devMin` $tmpMnt/$dev || exit   #revert to minimal /dev
  }
  updateInittab 's/^DEV.:/#&/g'   &&   #disable starting udev from inittab
  updateRC 'disable/*coldplug'
;;
 late|--late)
  mountRoot
  [ -e $tmpMnt/$devMin ] || {  #save original dev as devMin(imal)
    mv $tmpMnt/$dev $tmpMnt/$devMin || exit
  } #archive /dev for currently configured hardware (skip sockets)
  rm -f $tmpMnt/$dev
  (cd /dev && tar --warning=no-file-ignored -czf $tmpMnt/$dev *) &&
  updateInittab 's/^#\(DEV.:\)/\1/g' $inittab && #start udev from inittab
  updateRC '*coldplug' disable
;;
 disable|--disable)
  updateInittab 's/^DEV.:/#&/g' &&
  updateRC '*coldplug' disable
;;
 *) cat >&2 <<END
Configure recognition of installed devices -- 12/16/19 brent@mbari.org
 Usage:
  $self early   #delay boot up until all installed devices recognized
  $self late    #recognize new devices only after boot up completed
  $self disable #never recognize newly installed devices
 Notes:
  early is the default -- most flexible, but slow.
  $self late typically boots up about 20 seconds faster than $self early.
  $self "disabled" or "late" require that any kernel modules
  needed during boot be listed in /etc/modules
  Changes take effect on next boot.
END
  exit 9
esac
