#!/bin/sh
#Disconnect/Detatch the USB connected Iridium Handset
#so it will receive calls (RING)

. lockIridium || return

#terminate any data call in progress and
#ensure modem will simply report RING on incoming calls
/usr/sbin/chat -f /etc/ppp/iridium-detach.chat <$ATport >$ATport && return

#power cycle modem if above chat fails
/etc/ppp/reset-modem
return 1
