#!/bin/sh
#
#  ifdown [interface name]
#

. /usr/share/ifdownfn.sh

case "$1" in
  -*|*/*|'') #any flag is a request for help
    cat <<END >&2
usage:  ifdown [network interface or alias name]
        deconfigure and disable the specified network interface or alias
END
    exit 1
  ;;
esac

trap "gateUp; hostsUp; gateUpdated" EXIT TERM INT HUP QUIT

tracefn=/tmp/ifdown.trace
if [ -w $tracefn ]; then
  (date; echo "$@"; env) >>$tracefn
  exec 2>>$tracefn
  set -x
fi

ifDown "$@"
