#!/bin/sh
#
#  ifdown [interface name]
#

. /usr/share/ifdownfn.sh

case "$1" in
  -*|*/*|'') #any flag is a request for help
    cat <<END >&2
usage:  ifdown [network interface or alias name]
        deconfigure and disable the specified network interface or alias
END
    exit 1
  ;;
esac

#signal tunnel deamons that interface may close soon
for tunFn in /var/run/tunnel*.pid; do
  [ -s "$tunFn" ] && {
    tun=`cat $tunFn` && {
      kill -USR1 $tun && {
        for t in 9 8 7 6 5 4 3 2 1 0; do  #wait for tunnel daemon to die
          sleep 1
          kill -0 $tun 2>/dev/null || break
        done
      }
    }
  }
done

ifDown "$@"
gateUp
hostsUp
gatewayUpdated
