#!/bin/sh
#
#  ifup [interface name|definition file]
#
. /usr/share/ifupfn.sh

devfn=$1
mode=$2

case "$devfn" in
  "")  #take the interface definitions from the environment
    [ "${IFNAME}" ] || usage
    ifup_function $mode
  ;;
  
  -*)  #any flag is a request for help
    usage    
  ;;
  
  *) #anything else must be the name of an interface
    unset BOOTPROTO IPADDR NETMASK BROADCAST DHCPNAME
    unset NETWORK GATEWAY MTU AUTOSTART
    IFNAME="$devfn"
    cd /etc/sysconfig && {
      cfg=ifcfg-$IFNAME
      [ "$IFNAME" = lo ] && cfg=ifcfg-Lo  #make lo come up 1st!
      [ -r $cfg ] || cfg=if-default
      . ./$cfg
      ifup_function $mode
    }
esac
