#!/bin/sh
#
#  ifup [interface name|definition file]
#
usage() {
  cat <<END >&2
usage:  ifup [netInterface] {mode}
        configure and enable the specified network interface
        only bring up IFNAME if its AUTOSTART mode matches regex {mode}
        or Yes or No if the mode parameter is omitted
END
  exit 101
}

. /usr/share/netutils.sh

case "$1" in
  "")  #take the interface definitions from the environment
    [ "${IFNAME}" ] || usage
  ;;
  -*|*/*)  #any flag is a request for help
    usage
  ;;
  *) #anything else must be the name of an interface
    ifCfg $1
esac

[ "$IFNAME" ] || usage
ifUp $2

