#!/bin/sh
#
#  ifup [interface name|definition file]
#
. /usr/share/ifupfn.sh

tracefn=/tmp/ifup.trace
if [ -w $tracefn ]; then
  (date; echo "$@"; env) >>$tracefn
  exec 2>>$tracefn
  set -x
fi

ifUp "$@"
