#!/bin/sh
#sychronize real-time with Iridium network
#returns 0 if successful
#returns 1 if could not read time
#returns 2 if time formatted incorrectly
#returns 99 if serial port was locked

ATport=/dev/AT/iridium
ATlock=/var/lock/LCK..AT_iridium

[ -s $ATlock ] && owner=`cat $ATlock` && kill -0 "$owner" && {
  echo "$ATport is locked by pid $owner" >&2
  return 99
}
#output Iridium system time in a format suitable for date utility
#this also selects simple RING reports to ensure we're in the right mode
{
  flush
  echo -ne "ATE0;+CRC=0;+CCLK?\r"
  count=15
  while let --count && IFS=: read -rt 3 cclk dateTime; do
#echo -n "$dateTime" | hexdump -C >&2
    [ "$dateTime" ] && break
  done
} <$ATport >$ATport || {
  echo "Failed to read UTC time from $ATport" >&2
  return 2
}
itime=`echo -n "$dateTime" | tr -d '\r\n' | tr '/,' '- '`
[ "$itime" ] || {
  echo "Missing UTC time from $ATport" >&2
  return 1
}
echo "20$itime"
