#!/bin/sh
[ -z "$1" ] && {
  cat 2>&1 <<END
Modify /card and related links to allow specified rootfs to be a root filesystem
7/9/18 brent@mbari.org
END
exit 2
}
[ -d "$1" ] || {
  echo "$1 must be a preexisting directory!" 2>&1
  exit 3
}
top=`realpath $1` || top=$1
mount | grep " type rootfs " | while read rootfs on rootdir ignore; do
  [ "$rootdir" = "$top" ] && {
    echo "$1 must not be the current root directory"
    exit 1
  }
done

cd "$1" &&
rm  -rf card tmp &&
ln  -s  . card &&
mkdir -p var && cd var &&
mkdir -p log run lock &&

[ "$2" ] && {
  cd "$top" &&
  mkSWAPfile $2 $3 ||
  exit $?
}
echo "$1 may now be mounted as root filesystem"
