#!/bin/sh
iface=$1
[ "$iface" ] || {
  self=`basename $0`
  iface=`basename /proc/sys/net/ipv4/conf/e*`
  : ${iface:=ether}
  cat <<EOS >&2
Release DHCP lease on specified network interface -- 10/29/21 brent@mbari.org
optional 2nd argument is the (spoofed) MAC address whose lease is to be released
Usage:
  $self <network interface> {Ethernet MAC address}
Examples:
  $self $iface   #release lease held by this host
  $self $iface  01:02:03:80:81:83  #release lease of host with this MAC
Important Note:
  The specified network interface must not be in use.
  DO NOT disable the interface you are using to access this machine!
  Use breakDHCPlease instead of this script
EOS
exit 9
}

if [ -r /usr/share/netutils.sh ]; then
  . /usr/share/netutils.sh
  ifCfg $iface
  scriptDir=/usr/share/udhcpc
else
  IFNAME=$iface
  scriptDir=/etc/udhcpc
  hwaddr() {
    cat /sys/class/net/$1/address
  }
fi

mac=$2
[ "$mac" ] && {
  oldmac=`hwaddr $IFNAME` &&
  trap "ifconfig $IFNAME down hw ether $oldmac" EXIT HUP TERM INT QUIT PIPE &&
  ifconfig $IFNAME hw ether $mac || exit
}
#get a lease, release it and quit
ifconfig $IFNAME 0 &&
udhcpc -t 20 -fCRqni $IFNAME -s $scriptDir/release.script
