#!/bin/sh
prog=`basename $0`

[ "$1" ] && { cat >&2 <<END
Reroute traffic to ESPshore -- 9/30/25 brent@mbari.org
Select different route to ESPshore wireguard server
Intended to be invoked from wgatch
Usage:
  $prog
END
  exit 2
}

. /usr/share/bringUpDown.sh

case "`routeTo $ESPshore 2>/dev/null`" in
  "")  #there is no route to ESPshore
    case `cellState` in
      *OFF*)
        bringDownSat
        bringUpCell 9  #keep sat off 9 sec if there is no cell
     ;;
      *ON*)
        bringDownCell
        bringUpSat 5   #keep cell off 5 sec if there is no sat
     ;;
      *)  #turn all on if USB power controlled ports not working
        [ "$cellIface" ] && bringUpCell
        [ "$satIface" ] && bringUpSat
    esac
;;

  "$cellIface")
    bringDownCell
    bringUpSat 5
;;

  "$satIface")
    bringDownSat
    bringUpCell 9
;;

  *) #if another route has higher priority, create a specific route to ESPshore
    if isUp $cellIface && cellIP=`gateIPadr $cellIface`; then
      ip route replace $ESPshore via $cellIP dev $cellIface
    elif isUp $satIface && satIP=`gateIPadr $satIface`; then
      ip route replace $ESPshore via $satIP dev $satIface
    else
      startCell
    fi
esac
