#!/bin/sh
prog=`basename $0`

[ "$1" ] && { cat >&2 <<END
Reroute traffic to ESPshore -- 2/20/25 brent@mbari.org
Select different route to ESPshore wireguard server
Intended to be invoked from wgatch
Usage:
  $prog
END
  exit 2
}

. /usr/share/bringUpDown.sh

case "`routeTo $ESPshore 2>/dev/null`" in
  "")
    startCell
;;

  "$cellIface")
    bringDownCell
    bringUpSat 9
;;

  "$satIface")
    bringDownSat
    bringUpCell 30
;;

  *) #if another route has higher priority, create a specific route to ESPshore
    if isUp $cellIface; then
      ip route replace $ESPshore dev $cellIface
    elif isUp $satIface; then
      ip route replace $ESPshore dev $satIface
    else
      startCell
    fi
esac
