#!/bin/sh
self=`basename $0`
zoneinfo=/usr/share/zoneinfo
tz=$1
case $tz in 
  "")  cat 2>&1 <<END
Set timezone
Usage:  $self <timezone>
where <timezone> is the timezone name or absolute path to a tzdata file
If <timezone> does not begin with /, it is prefixed with $zoneinfo/

Examples:
  $self --list      #shows table of all available timezones
  $self US/Central  #Central Daylight Savings time
  $self PST8PDT     #Pacific Daylight Savings time
END
exit 2
;;
  /* )
;;
  -l*|--l* )
  cd $zoneinfo
  ls -R *
  exit
;;
  * )
    tz=$zoneinfo/$tz
esac

[ -r "$tz" ] || {
  echo "Missing tzdata file:  $tz" 2>&1
  exit 1
}
ln -sf $tz /etc/localtime

