#!/bin/sh
modem=$1
case "$1" in
  -*) self=`basename $0`
      cat <<END >&2
Display signal quality of indicated cellular modem -- 10/21/25 brent@mbari.org
by returning results from the AT+CSQ command
Usage:
  $self {path to modem's AT command port}
Example:
  $self /dev/ttyUSB2  #assuming modem's "AT" command port is ttyUSB2
  $self rnd1  #assuming modem's "AT" port is /dev/AT/rnd1
Note:
  Modem AT port may be omitted for Telit ME910 or Pantech UML295
END
  exit 2
;;
  '')
    by=/dev/serial/by-id
    modem=/dev/AT/me910
    [ -c "$modem" ] || {
      modem=/dev/AT/a76xx; [ -c "$modem" ]
    } || modem=`echo $by/usb-Pantech__Incorporated_PANTECH_UML295_*-if06`
;;
  /*)
;;
  *)
    modem="/dev/AT/$1"
esac
[ -c "$modem" ] || { cat <<END >&2
Not a valid serial port: $modem
END
  exit 1
}

iface=`basename $modem`
ATlock=/var/lock/LCK..AT_$iface
[ -s $ATlock ] && owner=`cat $ATlock` && kill -0 "${owner// }" && {
  echo "$modem is locked by pid $owner" >&2
  return 99
}
signal=`flock -w30 $modem /usr/sbin/chat -t5 REPORT +CSQ:\
  '' AT OK AT+CFUN=1 OK AT+CSQ +CSQ: 2>&1 <$modem >$modem || {
    echo "Failed!" >&2
    exit 8
}`
echo $iface: $signal
