#!/bin/sh
#Put USB connected Iridium Handset into sleep mode
#from which it can still receive calls (RING)

modem=/dev/AT/iridium

exec <$modem >$modem
#terminate any data call in progress and
#ensure modem will simply report RING on incoming calls
/usr/sbin/chat -t 9 '' "AT\r\d\p\p+++\d\p\p\c" OK AT+CRC=0 OK &&

#leave modem port open with its DTR line deasserted
holdopen dtroff
