#!/bin/sh
#initialize slip link's ip parameters

. /usr/share/netutils.sh

[ "$1" ] && IFNAME=$1
unset BOOTPROTO IPADDR NETMASK BROADCAST DHCPNAME
unset NETWORK GATEWAY MTU AUTOSTART
unset hosts resolv_conf ifPrep ifPost
cfg=$syscfg/ifcfg-$IFNAME
[ -r $cfg ] || cfg=$syscfg/if-default
. $cfg && ipUp && {
  echo $IFNAME IP=$IPADDR
  gateUpdated
}
