#!/bin/sh
: ${HOME:=/root} #in case invoked from inittab
: ${noGateDelay:=600}  #retry delay if no gateway
: ${pidFn:=/var/run/tunnel2shore.pid}
: ${portFn:=/var/etc/tunnel2shore.port}
: ${shore:="-p2323 `hostname`@ESPshore"}
export HOME
[ "$1" ] && { cat >&2 <<END
Bring up ssh tunnel to $shore for ssh and smtp
Retries every $noGateDelay seconds until network available
END
  exit 2
}
#kill any other instances
oldPID=`cat $pidFn 2>/dev/null` && kill -0 "$oldPID" 2>/dev/null && kill $oldPID
echo $$ >$pidFn

topIf() {
  #output the name of the top priority network interface
  local iface
  read -r iface gateway 2>/dev/null </etc/resolv.conf &&
  echo ${iface###}
}

while [ ! `topIf` ]; do
  echo "No Network Gateway -- retrying tunnel in $noGateDelay seconds"
  sleep $noGateDelay
done

fuser -sk 25/tcp
common="-ygNK 180 -L25:ESPshore:25"
[ -s $portFn ] &&
 ssh -oExitOnForwardFailure=yes $common -R`cat $portFn`:localhost:22 $shore || {
  sshPort=`ssh -y $shore tunnel close` && {  #request far side of tunnel close
    echo $sshPort >$portFn
    exec ssh $common -R$sshPort:localhost:22 $shore  #try again
  }
}
