#!/bin/sh
self=`basename $0`
. /usr/share/netutils.sh
prefix=ifcfg-
aliases=${prefix}\*

[ "$1" ] && { cat >&2 <<END
Update network interface alias symlinks $aliases -- 1/1/25 brent@mbari.org
END
  exit 9
}

fixLink() {
#create symlink $2 to $1 in $3 if $2 is a symlink or does not exist
#complain if $2 exists and is not a symlink
  [ ! -e "$3$2" -o -h "$3$2" ] && {
    echo "$1 = $2"
    ln -sf "$3$1" "$3$2"
  }
}

cd $syscfg && for cfg in `echo $aliases`; do
  [ -h "$cfg" ] && {
    realpath "$cfg" >/dev/null 2>&1 || {  #remove broken symlinks
      echo "Removing dangling symlink $cfg" >&2
      rm "$cfg"
    }
    continue
  }
  [ -e $cfg ] || continue
  suffix=${cfg#$aliases}
#  echo "$suffix"
  ifCfg $suffix
  [ "$IFNAME" ] || {
    echo "In $cfg: IFNAME unset" >&2
    continue
  }
  [ "$suffix" = "$IFNAME" -o "$suffix" = "$IFALIAS" ] || {
    echo "In $cfg: IFNAME or IFALIAS must be set to $suffix" >&2
    continue
  }
  [ "$IFALIAS" ] || continue
  [ "$IFNAME" = "$IFALIAS" ] && {
    echo "In $cfg: IFNAME and IFALIAS must be set to different strings" >&2
    continue
  }
  #finally found a cfg file that defines unique IFNAME and IFALIAS
  if [ "$suffix" = "$IFALIAS" ]; then
    fixLink $IFALIAS $IFNAME $prefix
  else
    fixLink $IFNAME $IFALIAS $prefix
  fi || echo \
    "Either $prefix$IFALIAS or $prefix$IFNAME should symlink to the other">&2
done
