#!/bin/sh
# unpack and patch portmap daemon for arm-linux -- 3/15/05 brent@mbari.org

: ${PORTMAPVERS:=portmap_5beta}
rm -rf $PORTMAPVERS && 
tar xzf portmap_5gentoo.tar.gz && 
cd $PORTMAPVERS &&
echo Done.
