#!/bin/sh
# unpack & patch wpa_supplicant daemon for arm-linux -- 12/25/24 brent@mbari.org

: ${wpaVersion:=2.7}
: ${wpa_supplicant:=wpa_supplicant-$wpaVersion}
rm -rf $wpa_supplicant && 
tar xzf $wpa_supplicant.tar.gz && 
#sed -i 's/-O2/-Os/g' `find -name Makefile` &&
[ ! -e $wpa_supplicant.patch ] ||
  cat $wpa_supplicant.patch | (cd $wpa_supplicant && patch -p1) && 
cp buildConfig-$wpaVersion $wpa_supplicant/wpa_supplicant/.config &&
echo Done.
