#!/bin/sh
# unpack & patch wpa_supplicant daemon for arm-linux -- 4/15/22 brent@mbari.org

: ${wpa_supplicant:=wpa_supplicant-2.7}
rm -rf $wpa_supplicant && 
tar xzf $wpa_supplicant.tar.gz && 
#sed -i 's/-O2/-Os/g' `find -name Makefile` &&
cat $wpa_supplicant.patch | (cd $wpa_supplicant && patch -p1) && 
cp buildConfig-2.7 wpa_supplicant-2.7/wpa_supplicant/.config &&
echo Done.
