#!/bin/sh
# build & install wpa_supplicant daemon for arm-linux -- 4/22/16 brent@mbari.org

: ${ARMGCC:=/arm}
: ${ARMSTRIP:=$ARMGCC/bin/strip}
: ${TARGETTOP:=${2-usr/sbin}}
: ${HOSTTOP:=${1-$HOME/armHost}}
: ${CC:=$ARMGCC/bin/gcc}
echo "Installing in $HOSTTOP"
echo "  for execution at $TARGETTOP on the ARM target"
TOP=$HOSTTOP/$TARGETTOP
cd wpa_supplicant-2.5/wpa_supplicant &&
cp ../../buildConfig .config || exit 2
make CC=$CC || exit 1
mkdir -p $TOP || exit 4
for prog in wpa_supplicant wpa_cli wpa_passphrase; do
  $ARMSTRIP $prog -o $TOP/$prog || exit 3
done
echo "Done."
