#!/bin/sh
#  Build backported kernel modules for updating ltibarm kernel
#  Binaries from mod-init-tools 
#    should already be installed in ~/linux/ltib/bin
#    (configure and make in ltib/rpm/BUILD/mod-init-tools-3.* to generate these)
#
#  install all modules in /lib/modules/*/updates directory
#  Many wireless devices require firmware which can be simply copied 
#  from desktop linux into /lib/firmware (see also the firmware directory here)
# -- 4/25/20 brent@mbari.org
#
: ${backported:=backported-3.*}
: ${LTIB:=~/ltib}
: ${KLIB:=$LTIB/rootfs.tmp}
: ${KLIB_BUILD:=$LTIB/rpm/BUILD/linux}

[ -d $KLIB_BUILD -a -d $KLIB ] || {
  echo "-->  You must first prep and build the ltib kernel with cmds below <--"
  echo "$ cd $LTIB"
  echo "$ ltib -p kernel -m prep
  echo "$ ltib -p kernel -m scbuild
  echo "$ ltib"
  exit 2
}
export KLIB KLIB_BUILD
start=`pwd` &&
cd $backported &&
ltibMake -j4 INSTALL_MOD_STRIP=1 modules_install &&
ln -sf $KLIB_BUILD/include/linux $LTIB/rootfs/usr/include &&
$start/updatedOriginal 'rm -f'

