#!/bin/sh
# build & install libpng for arm-linux
# -- 2/25/25 brent@mbari.org

: ${libpng:=v1.6.43}
: ${ARMGCC:=/arm}
: ${ARMSTRIP:=$ARMGCC/bin/strip}
: ${HOSTTOP:=${1-$HOME/armHost}}
: ${TARGETTOP:=${2-$HOSTTOP/usr/lib}}
: ${CC:=$ARMGCC/bin/gcc}

echo "Installing libpng $libpng in $HOSTTOP"
cd ${libpng} || exit
make -j4 &&
cp pnglibconf.h $ARMPREFIX/include &&
cd .libs &&
cp -a *.so* *.a $ARMPREFIX/lib &&
for so in *.so*; do
  if [ -h $so ]; then
    cp -a $so $TARGETTOP
  else
    $ARMSTRIP --strip-unneeded -o $TARGETTOP/$so $so
  fi || exit
done &&
cd .. &&
$CC -o pnginfo -I. ../pnginfo.c -L$ARMPREFIX/lib -lpng16 -lz &&
cp -a pnginfo $TARGETTOP/../bin &&
echo "Done."
