#!/bin/bash
#  Make startlight xpress kernel driver for ltib (arm) linux
: ${KERNEL_DIR:=~/ltib/rpm/BUILD/linux}
[ -d "$KERNEL_DIR" ] || {
  echo "$KERNEL_DIR is not an existing directory" >&2
  exit 1
}
: ${objs:="ccd.o sx_usb.o"}
[ -z "$KERNEL_VER" ] &&
  KERNEL_VER=`grep "Linux kernel version" $KERNEL_DIR/.config | 
              cut -sf2 -d: | tr -d "[:space:]"` &&
cd kernel &&
make clean &&
ltibMake all KERNEL_DIR=$KERNEL_DIR KERNEL_VER=$KERNEL_VER obj-m="$objs"
