#!/bin/bash
#  Make startlight xpress kernel driver for ltib (arm) linux
# revised: 6/13/18 brent@mbari.org
: ${KERNEL_DIR:=~/ltib/rpm/BUILD/linux}
: ${objs:="ccd.o sx_usb.o"}
: ${KERNEL_VER:=`cd $KERNEL_DIR; make kernelversion`} &&
: ${HOSTTOP:=`echo ~/ltib/rootfs.tmp`} &&
: ${INSTALL_DIR:=`echo ${HOSTTOP}/lib/modules/${KERNEL_VER}*`} &&

echo "Installing udev helpers in $HOSTTOP" &&
cp starlightXpress $HOSTTOP/lib/udev &&
cp *.rules $HOSTTOP/etc/udev/rules.d &&

cd kernel &&
make clean &&
ltibMake all KERNEL_DIR=$KERNEL_DIR KERNEL_VER=$KERNEL_VER obj-m="$objs" &&

echo "Installing kernel modules in $INSTALL_DIR" &&
[ -d $INSTALL_DIR/starlightXpress ] || {
  mkdir $INSTALL_DIR/starlightXpress || exit $?
}
cp -r *.ko $INSTALL_DIR/starlightXpress
