#!/bin/bash
# unpack & configure GNU screen for arm-linux -- 4/23/21 brent@mbari.org
: ${gitTop:=`realpath $(dirname $0)`}
: ${bashTop:=$gitTop/bash}
: ${HOST:=$ARMHOST}

[ -d "$bashTop" ] || {
  cd $gitTop &&
  git clone -b bash-5.1 https://git.savannah.gnu.org/git/bash.git $bashTop ||
    exit
}
cd $bashTop &&
configure --host=$ARMHOST --disable-help-builtin --disable-nls \
  CPPFLAGS=-I$ARMPREFIX/include LDFLAGS=-L$HOSTTOP/usr/lib &&
echo "Now, run arminstall"
