#!/bin/sh
# unpack & patch openssh for arm-linux -- 6/14/16 brent@mbari.org

: ${openssh:=openssh-7.2p2}
rm -rf $openssh && 
tar xzf $openssh.tar.gz &&
cd $openssh &&
ltibConfigure --without-openssl
echo Done.
