#!/bin/sh
# build & install stfp-server from openssh for arm-linux
#  -- 4/26/20 brent@mbari.org

: ${ARMGCC:=/arm}
: ${ARMSTRIP:=$ARMGCC/bin/strip}
: ${TARGETTOP:=${2-/usr/libexec}}
: ${HOSTTOP:=${1-$HOME/armHost}}
: ${CC:=$ARMGCC/bin/gcc}
echo "Installing in $HOSTTOP"
echo "  for execution at $TARGETTOP on the ARM target"
TOP=$HOSTTOP/$TARGETTOP
cd openssh-7.2p2 &&
ltibMake -j9 sftp-server &&
mkdir -p $TOP &&
for prog in sftp-server; do
  $ARMSTRIP $prog -o $TOP/$prog &&
  chmod +x $TOP/$prog || exit
done &&
echo "Done."
