#!/bin/sh
# /etc/rc.d/sysinit
# This file is used by inittab and init. Place here all the stuff you want
# to be done before any other system startup scripts are executed

# Ingore CTRL+C
trap ":" INT QUIT TSTP

# Set our Path
PATH='/bin:/sbin:/usr/bin:/usr/sbin'
export PATH

echo "MBARI ESP Embedded Linux    http://www.mbari.org   mailto:brent@mbari.org"
hostname -F /etc/HOSTNAME
hostname

mount -n -t proc proc /proc

if  test -x /sbin/dmesg  ; then
   if  test -f /etc/consolelog.level  ; then
	   . /etc/consolelog.level
   else
	   LOGLEVEL=1
   fi
   /sbin/dmesg -n $LOGLEVEL
fi

echo "" > /proc/sys/kernel/hotplug

mount -n -t sysfs sys /sys || exit $?

#initialize dev file system
mount -n -o mode=0755 -t tmpfs tmpfs /mnt
cp -a /dev/. /mnt
mount --move /mnt /dev
