#!/bin/sh
# /etc/rc.d/sysinit
# This file is used by inittab and init. Place here all the stuff you want
# to be done before any other system startup scripts are executed

# Ingore CTRL+C
trap "" INT QUIT HUP TSTP

# Set our Path
export PATH=/bin:/sbin:/usr/bin:/usr/sbin

echo "MBARI ESP Embedded Linux    http://www.mbari.org   mailto:brent@mbari.org"
hostname -F /etc/HOSTNAME
hostname

mount -n -t proc proc /proc
mount -n -t sysfs sys /sys

#initialize dev filesystem if not yet mounted
if mountpoint -q /dev; then #using devtmpfs
  mknod /dev/ppp c 108 0
else
  devtgz=/dev/.dev.tgz
  mount -n -t tmpfs dev /mnt &&
  if [ -e "$devtgz" ]; then
    tar -C /mnt -xmzf "$devtgz"
  else
    cp -a /dev/* /mnt
  fi && exec mount --move /mnt /dev
fi
ln -s /proc/self/fd /dev
mkdir -p /dev/pts /dev/shm

