#!/bin/sh
# /etc/rc.d/sysinit
# This file is used by inittab and init. Place here all the stuff you want
# to be done before any other system startup scripts are executed

# Ingore CTRL+C
trap "" INT QUIT HUP TSTP

# Set our Path
export PATH=/bin:/sbin:/usr/bin:/usr/sbin

echo "MBARI ESP Embedded Linux    http://www.mbari.org   mailto:brent@mbari.org"
hostname -F /etc/HOSTNAME
hostname

mount -n -t proc proc /proc
mount -n -t sysfs sys /sys

#initialize dev filesystem
mount -n -t tmpfs dev /mnt &&
tar -C /mnt -xmzf /dev/.dev.tgz &&
exec mount --move /mnt /dev
