#!/bin/sh
#start an initial espclient on the current tty
#intended to be invoked from /etc/inittab as:
# esp:3:respawn:/sbin/getty -L baud -nl /etc/esp/client ttyDevice
 
exec su - esp -c "exec sh -ic \"exec espclient --begin '' --wait mooring\""
