#!/bin/sh
#start an initial espclient on the current tty
#intended to be invoked from /etc/inittab as:
# esp:3:respawn:/sbin/getty -L baud -nl /etc/esp/client ttyDevice
 
su - brent -c "exec sh -ic \"espclient --wait brent\""
